### ISSUE TITLE
GUI : FED : Server Health - Event logs

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1211]
## Overview
Recreate the event logs page in Vue.js based on new design.
- Events: /redfish/v1/Systems/system/LogServices/EventLog/Entries

## Tasks
- [ ] Verify when Redfish API is ready (use REST API if not ready). 
- [ ] Add route and all route meta data
- [ ] Create page using page components
- [ ] Needs filter and export components (add blockers for component stories)
- [ ] Need to write table to be dynamic
    - Reference Code column only needed by IBM

### Actions
- [ ] Export
- [ ] Delete
~~Resolved - Not part of the Redfish API yet~~

## InVision Prototype
https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319141765_01-Event-Logs

https://ibm.invisionapp.com/share/QANZHJKP74E#/319398050_Event_Log

## Screenshots
![01-event-logs-05@2x](https://user-images.githubusercontent.com/8097306/82241602-4a575880-98f1-11ea-9abc-4e37807efde3.png)

**Comment by yoshiemuranaka** [comment]
Breaking this down into a few commits:

- [ ] Create page/table with basic sort and filter by severity
- [ ] Add option to filter by date range
- [ ] Add table bulk actions (Export and delete–resolved not available yet)
- [ ] Add pagination
- [ ] Row expansion with details (some detail properties aren't available yet)

**Comment by yoshiemuranaka** [comment]
Chatted with @derick-montague and @ryanarnell about removing the time input field in the table filter because it adds a lot of complexity in the code. Decided it is not worth the effort right now, but may revisit in the future
