### ISSUE TITLE
GUI : FED :  Server Health - Sensors

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1213]
## Overview
Recreate page in Vue.js

## Tasks
- [x] Verify if Redfish API is ready
- [ ] Add route and all route meta data
- [ ] Create page using page components
- [ ] Verify design (filter layout, export button placement)
- [ ] Determine if new components or layout required and verify with design
- [ ] Include language translation
- [ ] Include table sorting by column

## Resource
- [SensorCollection for Redfish](https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/22496 )

**Comment by derick-montague** [comment]
@gtmills we are not sure about the endpoint for sensors. Looking for some guidance when you're back.

**Comment by yoshiemuranaka** [comment]
```
redfish/v1/Chassis/chassis/Sensors
redfish/v1/Chassis/chassis/Thermal
redfish/v1/Chassis/chassis/Power
```

**Comment by yoshiemuranaka** [comment]
- Status in tables will be indicated visually with small dot to the left of status label
- We will use the bootstrap provided sort icons in header
- Table header sort icons will be positioned to the left of the column header label

![status-sort](https://user-images.githubusercontent.com/8097306/77005777-9f411780-691e-11ea-89a0-bfa6b77acc91.jpg)

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/30528

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/30528 merged
