### ISSUE TITLE
GUI : FED : Server Control - Reboot BMC

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1218]
## Overview
Recreate page in Vue.js

## Tasks
- [x] Add route and all route meta data
- [x] Create page using page components
- [ ] Determine if new components or layout required and verify with design
- [ ] Include language translation

### Concerns
- Restart time is not part of the Redfish API. Unclear the importance to users.

**Comment by yoshiemuranaka** [comment]
```
curl -k -X POST https://${bmc}/redfish/v1/Managers/bmc/Actions/Manager.Reset -d '{"ResetType": "GracefulRestart"}'
```

**Comment by yoshiemuranaka** [comment]
```
When you reboot the BMC, your web browser loses contact with the BMC for several minutes. When the BMC is back online, you must log in again. If the Log In button is not available when the BMC is brought back online, close your web browser. Then, reopen the web browser and enter your BMC IP address. 
```

Not sure if this information is still accurate? Tried rebooting and wasn't kicked off. Should we revisit now?

**Comment by yoshiemuranaka** [comment]
@ryanarnell @derick-montague @gtmills

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29521
