### ISSUE TITLE
GUI: FED: Server Control - Serial over LAN

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1219]
## Overview
The current Serial over LAN design allows for the following functionality:
1. Open SoL console within the application
2. Open the SoL console in a new windows without the application navigation to create an experience that is closer to a command line experience 

## Tasks
- [ ] Add route and all route meta data
- [ ] Create page using page components
- [ ] Add the SoL console to the new design
- [ ] Include language translation
- [ ] Replace `courier-new` font with better font for CLI
    > Most of the uses of monospace font within the openbmc web interface are presenting very "terminal-like" data. The Courier family is good because it is universal, but it isn't considered a great font for terminal work because it can be difficult to read compared to other fonts. Can we explore a more modern font, such as the Menlo / DejuVu / Bitstream Vera Sans Mono family? While none of them are universal on their own, I think if you specify all 3 you'll get coverage on MacOS / Windows / Linux respectively (and all 3 are nearly identical fonts).

## Tips and Suggestions
- Brief overview of Serial over LAN
    - https://en.wikipedia.org/wiki/Serial_over_LAN
- Use the files listed below as a reference for the node modules needed to create and connect the SoL console. 
- Take your time and learn about the `xterm` node module
    - https://www.npmjs.com/package/xterm
    - https://github.com/xtermjs/xterm.js/
- In order for the SoL console to work, the system needs to be powered on. You need to reserve a machine in order to power it on and off
- We are not concerned about text decoding for IE 11 since that is not a browser that we expect is being used by our users. This is documented starting at line 39 in the `serial-console.js` file.

## Files to for reference
- Repository: https://github.com/openbmc/phosphor-webui

### serial-console 
- `/app/common/directives/serial-console.js`
- `/app/common/directives/serial-console.html`

### remote-console-controller
- `/app/server-control/controllers/remote-console-controller.html`
- `/app/server-control/controllers/remote-console-window-controller.html`
- `/app/server-control/controllers/remote-console-window-controller.js`

**Comment by Srisuk** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/32632
