### ISSUE TITLE
GUI : FED : Server Control - IP KVM 

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1220]
## Overview
Recreate page in Vue.js.

## Tasks
- [ ] Add route and all route meta data
- [ ] Create page using page components
- [ ] Determine if new components or layout required and verify with design
- [ ] Include language translation

**Comment by derick-montague** [comment]
Added help wanted story in openbmc/webui-vue repo

**Comment by derick-montague** [comment]
Progress sync meeting on 6/17/20 determined this feature can be supported by the community since IBM does not need this functionality today. Closing this story since it is already added to the webui-vue repo.
