### ISSUE TITLE
GUI : FED : Server Control - Virtual Media

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1221]
## Overview
Recreate page in Vue.js
## Tasks

- [ ] Add route and all route meta data
- [ ] Create page using page components
- [ ] Determine if new components or layout required and verify with design
- [ ] Include language translation

**Comment by derick-montague** [comment]
Added help wanted story in openbmc/webui-vue repo

**Comment by derick-montague** [comment]
Not needed for IBM systems. Community will be providing this functiionality.
