### ISSUE TITLE
GUI : FED : Server Configuration - Network settings

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1222]
## Overview
- [ ] Recreate network settings page in Vue.js

## UX Flow / Interaction Requirements
- [ ] Feature breakdown

## Final Invision Mockup
- [ ] https://ibm.invisionapp.com/d/main#/console/15347903/319333952/preview

## cURL Commands
```
export bmc=<add IP address>

// Get token
export token=`curl -k -H "Content-Type: application/json" -X POST https://${bmc}/login -d '{"username" :  "root", "password" :  "0penBmc"}' | grep token | awk '{print $2;}' | tr -d '"'`

// Get info for the first interface
curl -k -H "X-Auth-Token: $token" https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

// Patch - Add new second or update second Static IP Address
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"IPv4StaticAddresses": [{},{"Address": "10.6.6.8"}]}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

// Patch - Add new second or update second Static IP Address include Gateway and SubnetMask
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"IPv4StaticAddresses": [{},{"Address": "10.6.6.8","Gateway": "0.0.0.0","SubnetMask": "255.255.254.0"}]}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
```

## Notes

- **SME**: Ratan Gupta
-  Slack: #network_info
-  Research: https://ibm.ent.box.com/notes/428875358806

- [ ] Need to revisit once default gateway is available in redfish 
Redfish(Network):Modified IPv4 addresses to use Default gateway
https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/24106
- [ ] UI work around for default gateway is to use the first ipv4 static addresses' gateway as the gateway for all ipv4 static configurations

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in DAP

### Tasks
- [x] Add route and all route meta data
- [x] Use updated design - https://github.com/ibm-openbmc/dev/issues/971
https://ibm.invisionapp.com/d/main?redirHash=#/console/15354657/319398051/preview?scrollOffset=483
- [x] Create page using page components
- [ ] Determine if new components or layout required and verify with design
- [ ] Include language translation

**Comment by derick-montague** [comment]
@ryanarnell @jandraa - Can someone help me remember how we were planning to support IPv6 in the UI?

**Comment by dixsie** [comment]
Related backend changes:

- [ ] **Ready 3/16** Support for NameServers & StaticNameServers https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/25804**

- [ ] **WIP** Backend changes for Populating Nameservers(DNS & Static) https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/26115)

- [ ] 
[Redfish-Ethernet Inf] Enable Read/Write for FQDN
 https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/30167

**Comment by dixsie** [comment]
**Questions**

**Design:**

- [ ] Should configuring an interface set that interface to enabled? If so, how should it be disabled?

**Backend:**
- [ ] I see the `StaticNameServers` array for the Static DNS name servers. Where do `DNS server IP addresses` come from for DHCP (is it in the `EthernetInterface/eth` endpoint)? Is it called something else on the backend? 

- [ ] Is there a difference between `redfish/v1/Systems/system/EthernetInterface` and `redfish/v1/Managers/bmc/EthernetInterface` ? Which should be used to `GET` and `PATCH`?

- [ ] Is there a `domainname` property in Redfish?

- [ ] Are the `IPv4Addresses.Address` read only if the `IPv4Addresses.AddressOrigin` is `Static`?

- [ ] Is default gateway the same for both ipv4 and ipv6?

**Comment by dixsie** [comment]
**Unable to modify existing IPv4 config:**

- [ ] Network Settings: Static IPv4 Configuration - PATCH doesn't return patch properties https://github.com/openbmc/bmcweb/issues/123

- [ ] Network Settings: Static IPv4 Configuration - PATCH 200 response does not persist https://github.com/openbmc/bmcweb/issues/124

**Comment by dixsie** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/32667/2

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/32667 merged
