### ISSUE TITLE
GUI : FED : Access Control - LDAP

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1226]
## Overview
Recreate page in Vue.js

## Tasks
- [ ] Verify if Redfish API is ready
- [ ] Add route and all route meta data
- [ ] Create page using page components
- [ ] Determine if new components or layout required and verify with design
- [ ] Include language translation

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31481
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31529

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/31529 merged
