### ISSUE TITLE
GUI : FED : Access Control - SSL certificates

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1228]
## Overview
Recreate page in Vue.js

## Tasks
- [ ] Verify if Redfish API is ready
- [ ] Add route and all route meta data
- [ ] Create page using page components
- [ ] Verify using consistent Save Form pattern
- [ ] Determine if new components or layout required and verify with design
- [ ] Include language translation

**Comment by yoshiemuranaka** [comment]
Breaking up into three commits 
- [ ] Basic page with ability to view, add, replace, delete certificates
- [ ] Banner/messaging for expiring certificates
- [ ] Generate CSR code

**Comment by yoshiemuranaka** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/30697
