### ISSUE TITLE
GUI : Application Header Content

### ISSUE THREAD

**Issue by nicoleconser** [ibm-openbmc/dev#1292]
## SME
NA

### Use Case
As an admin or SSR, I need to be able to see system information on the top for easy identification and get a high level status overview of the system health and power.
As a PE, I want all screenshots shared with me to have system information on the top.

### Invision prototypes
https://ibm.invisionapp.com/d/main#/console/15347903/319551593/preview

### References/Resources
- Related story: #1759 Responsive Site Header (closed) 
- Related story: #2424 Site Header Improvement (closed) 
- Related story: #2211 https://github.com/ibm-openbmc/dev/issues/2211
- [Feature discovery doc](https://ibm.ent.box.com/notes/827239298636)
- [Mural exploration](https://app.mural.co/t/ibmpower1831/m/ibmpower1831/1582793816628/db75cbe89d805f79e3f646ef819794d4c4e46cf8)

### Tasks
- [ ] Create design review story in webui-vue repo
- [ ] Send email to community sharing the design review story
- [ ] Post in story in the discord webui channel

### References
- eBMC Feature Item: 4.7
- [Link to Discovery folder](https://ibm.ent.box.com/notes/768289701177)

### UX Flow / Interaction Requirements
- [ ] Small size 320px: No extra information.
- [ ] Medium size 578px to 1200px: machinetype-model and serial number only. This is required in all screenshots so that PEs can identify the machine. 
- [ ] Large size, greater than 1200px: System name (assettag), machinetype-model and serial number. 

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

## Tasks
- [ ] ASMI Inventory
- [ ] Create assumptions and validate with PEs

__________

### Process pending / in progress
- Consider including a visual indication of a process that is in progress or pending. An indication might be a simple "FYI" notification OR might be a warning to the user that they cannot / should not perform certain operations until the process(es) is complete.
- [May not be possible as MVP](https://github.com/ibm-openbmc/dev/issues/1292#issuecomment-798665657)
- Verify that Redfish supports this and if not, what is the scope of work to support by the backend

Example: 
> User selects a different value for the "Logical memory block size" (BIOS setting) and clicks Save Settings, but this doesn't take effect until next IPL.

### Overall consistency
- Verify that the icons / verbiage in the header matches other pages in the GUI, such as Firmware and Error Log.

### Refresh button
- Want to make sure that our users' understanding of what this button does matches its intended use. 
    - We've encountered some friction on this.

### Header items we've lost from ASMI
Several end users have pointed out information that is missing from our Vue header, that would be useful to see at all times: 

### Firmware Level
- "It's very helpful that the ASMI interface displays the firmware level of the server in the upper right corner of the GUI." (feedback from 6 Sales Reps during Masters 2019) The reasons were:
    1. this is the first thing Support asks a customer for
    1.  it needs to be referenced from multiple screens. 

### System name** 
- Added to the header as the Asset Tag in #2780 

### what else are we missing?

**Comment by derick-montague** [comment]
Closed: Research will be completed as part of #1759

**Comment by nicoleconser** [comment]
Another consideration is to add **System name** to the header (not necessarily editable from the header, but viewable for quick reference from any page the user is on). 

Recently, a customer (very randomly - we did not ask, and we were not focusing on the header) pointed out that _System name_ is missing from the header in our Vue prototypes. She stated that _System name_ is useful to see at all times, because it gives you a sense of "where I am" (i.e. I have 1000s of servers in my data center - and 12 GUI tabs open in my browser - which server am I on?). 

@ParishrutB is currently considering making **System name** editable from the Overview screen, as it was in the Angular app. 

Full Slack conversation is [here](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1595976814152100). 

**side note to prevent confusion:** It was determined during a GUI workgroup meeting that **Hostname** is not important enough information to live in the Header, but _Hostname_ is different from _System name_.

**Comment by nicoleconser** [comment]
@ParishrutB's Mural with initial observations: https://app.mural.co/t/ibmpower1831/m/ibmpower1831/1582793816628/db75cbe89d805f79e3f646ef819794d4c4e46cf8

**Comment by nicoleconser** [comment]
Do we need copyright info in our header? Is this removed from OpenBMC because it is open-source? 
![Screen Shot 2020-08-03 at 2 09 24 PM](https://user-images.githubusercontent.com/15746733/89218096-0d673d80-d593-11ea-8aeb-b61b9730351c.png)

**Comment by derick-montague** [comment]
I believe that is around ASMI, so I don't think so since this is open.

**Comment by derick-montague** [comment]
Community Design work group adding the system name to the header.

Need to confirm with users if:
1. Should include FW level in the header
1. Update key access expiration information in header
1. Since we are using OpenBMC is copyright info still required in GUI? @mzipse @gtmills

**Comment by gtmills** [comment]
> Since we are using OpenBMC is copyright info still required in GUI?
I vote no. Have someone we can ask though?

**Comment by derick-montague** [comment]
I was leaning no also. I am not sure who to ask? @mzipse?

**Comment by nicoleconser** [comment]
Found in [Problem Statement research](https://ibm.box.com/s/k3f9kzm527ajooymfrxz46sas93sqtnz) doc (under _Known ASMI GUI pain points_): 

- If the user changes the original (factory) name of the server to something custom like **zzfpitc11**, then the only way to know the original name (the actual machine type) is by **logging out**
- This **original** system name only lives on the login screen **_before you log in_**

**Comment by ben-bacon** [comment]
[Here are two directions](https://ibm.invisionapp.com/share/NKO0EUY8CZ6) we could take to include the metadata listed above in the UI shell in subtle ways. 
- Direction 1 uses existing components, putting system name in the nav bar and firmware version in the side panel
- Direction 2 introduces the User Panel drawer which is sort-of like a beefed-up dropdown popover. Both info is placed in here, and also introduces the section for expansion of other future customization options.

**Comment by derick-montague** [comment]
@ben-bacon The link in the comment above links to the Security Panel mocks. Can you update it to the application header directions?

**Comment by derick-montague** [comment]
The plan will be to only add the system name in the header, however, we need to determine where the user can edit the system name. @ParishrutB let's make that part of #2211, I will add it to the list.

**Comment by gtmills** [comment]
> • System name — details in comments 

Will call AssetTag 
 curl -k -X PATCH -d  '{"AssetTag": "Paramo"}'  https://${bmc}/redfish/v1/Systems/system/

This merged into master today https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/37823

Note: I believe AssetTag is more commonly used in the industry. 
Can we call this `AssetTag (System Name)` or `System Name (Asset Tag)`

**Comment by derick-montague** [comment]
> Can we call this AssetTag (System Name) or System Name (Asset Tag)

I am a little lost on this part.

**Comment by gtmills** [comment]
Like I think the name should include "AssetTag"

**Comment by derick-montague** [comment]
I am not sure if we need to reopen this. Is the thought that we need to revisit the terminology with users?

**Comment by gtmills** [comment]
I accidently closed 🤦

**Comment by derick-montague** [comment]
> Process pending / in progress — Consider including a visual indication of a process that is in progress or pending. An indication might be a simple "FYI" notification OR might be a warning to the user that they cannot / should not perform certain operations until the process(es) is complete.

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/45923
