### ISSUE TITLE
GUI : Realtime Progress Indicators

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1303]
## Stakeholders
**BMC SME**: @manojkiraneda, @sunharis 
**RAS SME**: Justin Thaler
**IBM i SME**: Randy Tomfohrde
**PE**: Russ Young

## Research / Design

Discovery doc: https://ibm.ent.box.com/notes/806689559385

### Summary
These are codes that are displayed to the user in real time. It helps the user understand the progress of server status. It is not clear how push notifications will be supported.

- [x] Boot progress codes? 
- [x] How and where will these be displayed?

## User Story
As a system admin/PE/SSR
I need to observe the POST codes update in real-time while performing a system operation 
in order to troubleshoot and observe whether the process is running properly or not.

### InVision Prototype
- Upstream https://ibm.invisionapp.com/d/main#/console/15347903/319977112/preview
- Downstream https://ibm.invisionapp.com/d/main#/console/15347903/319985545/preview
Note differences in Page title and Export all button copy. 

**Note changes:** 
1. Page name for upstream: POST codes logs
2. Page name for downstream: Progress logs
3. Real time codes button name (for both pages): "View real-time codes"
4. Export all button: Primary button with copy "Export all"
5. Layout reference:  [Mockup](https://ibm.invisionapp.com/d/main#/console/15347903/319992746/preview)
![image](https://user-images.githubusercontent.com/61419136/120799189-0a92fb80-c55c-11eb-83d9-d80763f02a78.png)

### Tasks
- [ ] Create design review story in webui-vue repo
- [ ] Send email to community sharing the design review story
- [ ] Post in story in the discord webui channel

## References
- eBMC Feature Items 1.0.8 and 2.5.4
- [ ] [Link to Discovery folder](https://ibm.ent.box.com/notes/806689559385)

### Related Development Stories
#1086 : Store the last progress code in SRC hex data word 4

# FED
### UX Flow / Interaction Requirements
- [ ] The new window should be able to accomodate hex codes.
- [ ] Show 50 logs on first load.
- [ ] Attribute text for row buttons: "Export log" and "Download additional data"

### cURL Commands and Redfish Response
~~`/redfish/v1/Managers/BMC/LogServices/Progress`~~
```
curl -k -H "X-Auth-Token:$bmc_tokens" -X GET <IP Address>/redfish/v1/Systems/system/LogServices/PostCodes/Entries
{
  "@odata.id": "/redfish/v1/Systems/system/LogServices/PostCodes/Entries",
  "@odata.type": "#LogEntryCollection.LogEntryCollection",
  "Description": "Collection of POST Code Log Entries",
  "Members": [
    {
      "@odata.id": "/redfish/v1/Systems/system/LogServices/PostCodes/Entries/B1-1",
      "@odata.type": "#LogEntry.v1_4_0.LogEntry",
      "Created": "2021-02-09T01:38:32+00:00",
      "EntryType": "Event",
      "Id": "B1-1",
      "Message": "Boot Count: 1: TS Offset: 0.0000; POST Code: 0x4331303031463030",
      "MessageArgs": [
        "1", <--- Boot Count
        "0.0000", <--- Time Stamp Offset
        "0x4331303031463030" <--- Progress Code
      ],
      "MessageId": "OpenBMC.0.1.BIOSPOSTCode",
      "Name": "POST Code Log Entry",
      "Severity": "OK",
      "AdditionalDataURI" : "/redfish/v1/Systems/system/LogServices/PostCodes/attachment/B1-1"
    },
```

- [ ] Add Redfish response

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
## Info from IBM i SME: 
This is the same as 1.1.8 t maybe just different terminology or different levels.
Boot is a newer term used by PHYP/FSP/PFW .. it implies the firmware is loading and is starting. 
In the IBM i we called it IPL (initial program load)  progress history and is really the  system reference codes(SRCs). 

In reality we have 3 levels of progress which is reflected in the SRC ranges.
When PHYP is loaded and started, this is the boot, .. and generally has SRCs in the range C2xxxxxx,  D2xxxxxx

And if an error occurs it's in the B2xxxxxx range.. 
Then when a IBM i partition is started, the SLIC code uses theses ranges  C5xxxxxx, C6xxxxxx.. and if an error occurs B6xxxxxx.

Then IBMi starts the operating system and the range is C9xxxxxx and if an error occurs B9xxxxxx

**Comment by derick-montague** [comment]
It has been suggested by @ryanarnell that the progress logs be added to the power server operations page based on previous research by @jandraa. Some other discovery suggests that it would be included as part of the Overview page, but that is also in question. Part of this story is to determine where these logs should be displayed. Some of the options include:
- Overview page
- Server power operations page
- Event logs page

**Comment by ryanarnell** [comment]
Correct. We found out that users and IBM tests personals have the real time progress indicator open in a new tab just to see if the system halted during a power operation. In ASMI they also have previous progress indicator and progress indicator history page. 

<img width="1178" alt="Screen Shot 2020-05-05 at 3 17 41 PM" src="https://user-images.githubusercontent.com/4976631/81112098-bf836080-8ee3-11ea-967e-be521a7fbf77.png">

**Comment by derick-montague** [comment]
Also called Boot time progress and Host Progress codes

**Comment by spinler** [comment]
@derick-montague Have you received any requirements that the progress SRC details  (from clicking the 'show details' after selecting an indicator on ASM) are still desired, or just the 8 character string, like C2001122?

**Comment by derick-montague** [comment]
@spinler We have not focused that deep on progress indicators yet. Is this something that would be helpful for you to understand now?

**Comment by spinler** [comment]
@derick-montague Nah, I don't think we'll be getting to this for quite awhile still so there is time.

**Comment by derick-montague** [comment]
Slack conversation: power.slack.com/archives/C0Q6TQP5Z/p1592238708364400

In ASMI Realtime indicators is a window that is opened that polls the backend and updates SRC codes displayed in the window. We likely would not want that and could consider using toast messages.

**Comment by nicoleconser** [comment]
So far, when **Real-time progress indicator** has come up during interviews, users have commented that it is extremely useful in its current (pop-up modal) form. 

We can definitely do further research to understand more and assess where it makes the most sense to live in the new GUI — on the log page, dashboard, or perhaps as a standalone page.

**Comment by nicoleconser** [comment]
**notes from June sync-up:** 
**Maury** believes the state does not change during runtime; **Russ:** there are exceptions if standalone – realtime progress indicators include error codes – mirrors exactly what would be on the Op panel. Talk to **Matt Spinler**.

**Comment by derick-montague** [comment]
Original comment on 7/1/20: https://github.com/ibm-openbmc/dev/issues/1483#issuecomment-652714631

Slack conversation about Realtime / Progress Logs being part of event logs. https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1592238708364400

Summary: Would need some discussion about showing anything beyond SRC codes. In ASMI, realtime events is a new window that listens for changes and displays the code sent from the backend. If we wanted something similar, we could use toast messages.

It should be noted that there is also log records for all those codes that can be viewed later. It is possible that we will need both logs and the user notification.

**Comment by nicoleconser** [comment]
Need to find out if progress codes refer to FSP and/or server, and if that will be the same with BMC.

**Comment by ParishrutB** [comment]
05/18/2021 Discussion with Derick, Parishrut, Priyanka, Nicole, Sandeepa

- Use case: Giving the user some information that a process is going on or is stuck. For this, backend is planning to introduce the Task Service for giving granular progress updates for tasks like Firmware Update, Dumps, etc. This was discovered in the latter stories. Real time POST codes indicators is not required for this use case.
- Use case: While troubleshooting, user can observe POST codes being updated in real time. This is the only use case that real time POST codes indicators is useful for. 

Design decision: 
- Real time POST codes will open in a new window.
- Link to open them will be available on the POST code log page.

**Comment by derick-montague** [comment]
I expect this is supposed to be a FED story. Is that accurate @ParishrutB ?

**Comment by ParishrutB** [comment]
Yes

**Comment by derick-montague** [comment]
We are expecting to be able to do this downstream with Redfish events.

**Comment by gtmills** [comment]
This is downstream. Could we pull in downstream?

**Comment by derick-montague** [comment]
The Redfish events are ready to subscribe to downstream? We are not planning on implementing polling.

**Comment by gtmills** [comment]
> The Redfish events are ready to subscribe to downstream? We are not planning on implementing polling. 

Yes. https://github.ibm.com/openbmc/bmcweb/pull/105/files 
I would recommend Redfish events before implementing polling

**Comment by derick-montague** [comment]
Sandeepa will research on subscribing to redfish events and talk with @sunharis.

**Comment by sandeepasingh116** [comment]
Slack conversation about implementing event listeners :
https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1628674060264600

**Comment by sandeepasingh116** [comment]
The following was discussed at design exchange meeting:
- Sunitha said that she will be asking the test team to test SSE on backend, she'll also have to check which events come out as SSE as right now all events come out as push style event.

- Second option was polling, which is not preferred. In case of real time 
indicator we have can still open the connection when window is opened and listen to events by polling and close the window and stop the connection, but there are other logs like event logs, power state which would require constant polling and that's not good performance wise

**Comment by dixsie** [comment]
@sandeepasingh116, @mzipse and @gmills and I discussed following up on this story at the design exchange this Tuesday

**Comment by dixsie** [comment]
@sandeepasingh116 Possible path & interface https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1632418198306000?thread_ts=1632405103.285200&cid=C0Q6TQP5Z

**Comment by mzipse** [comment]
Work is complete.  Closing.
