### ISSUE TITLE
GUI : BMC Command Line / Service Login Web Based SSH

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1490]
## SMEs
**BMC**: @geissonator, @joseph-reynolds, @patelabhishek9893 
**PE**: Russ Young
**RAS**: George Ahrens

### Summary
The CE (service) Login will have a way to SSH via the GUI. CE Login is going to require using a certificate, the GUI since you already did this certificate step, means SSH via the GUI is just easier. Still some question if we are going to do this. 

This feature was referred to as BMC Command Line when discovery took place and the IA for eBMC was drafted. The stakeholders are referring to this feature as **CE Login Web Based SSH.**

### End Users
- Paul - IBM Product Engineer

### User Story
- As a PE/SSR, I need to issue a BMC command for settings that have no GUI equivalent, so that I can troubleshoot an issue for the customer. 
- As a PE/SSR, I need to test a BMC command for settings that are not behaving properly in the GUI, so that I can debug a GUI operation and check if it's working or misbehaving.  

### InVision Prototype
- Service login consoles https://ibm.invisionapp.com/d/main#/console/15347903/320050117/preview
- Serial over LAN console https://ibm.invisionapp.com/d/main#/console/15347903/320050507/preview

### Tasks
- [ ] Create design review story in webui-vue repo
- [ ] Send email to community sharing the design review story
- [ ] Post in story in the discord webui channel

### References/Resources
- eBMC Feature Item: 3.6.4 BMC Command Line
- [Feature discovery folder](https://ibm.ent.box.com/files/0/f/113289377312)

### UX Flow / Interaction Requirements
- [ ] Feature breakdown

### cURL Commands and Redfish Response
- [ ]  Add wss://${window.location.host}/bmc-console in websocket plugin line 77 

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by gtmills** [comment]
Joseph P. Reynolds 
Ping.  We are talking about this again in the eBMC (CELogin) security workshop.   @Russel Young claims that he and customers will need this access from the browser to facilitate faster service calls and better customer satisfaction.

Joseph P. Reynolds 
The issue is: Some customers only have browser access and don’t have SSH access.  So they need SSH access via their web browser.

**Comment by derick-montague** [comment]
Implementation discussion: https://ibm-systems-power.slack.com/archives/GQ8H06RC5/p1590680210003800

**Comment by nicoleconser** [comment]
Per Joseph Reynolds: 
- If the BMC CLI service is disabled via #612 then no one has access. 
- If enabled, then you need (1) a BMC user account, and (2) that account needs to be an Admin role in the 'ssh' group. 

see: [SSH access requires priv-admin instead of ssh #3643](https://github.com/openbmc/openbmc/issues/3643)

**Comment by priyanka-pillai97** [comment]
### Internal users slack discussion: 
https://ibm-systems.slack.com/archives/G01JLPJKVG9/p1619103268068000
https://ibm-systems.slack.com/archives/G01JLPJKVG9/p1619103393070500

**Comment by derick-montague** [comment]
We need further review of the lofi to determine what features are possible before it will be ready for implementation.

**Comment by priyanka-pillai97** [comment]
Conversation with backend regarding responses - 
1. The GUI will be able to display the response
2. Copying the response - The current plan is the backend will just be a websocket similar to SOL. The GUI can store this "response" and export it in whatever format it wishes.

[Link to the conversation ](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1623855917212700?thread_ts=1623762612.158600&cid=C0Q6TQP5Z)

**Comment by derick-montague** [comment]
This will be coupled with the PHYP command line #1492

**Comment by dixsie** [comment]
ACF work should be finished first in order to test command line.

**Comment by dixsie** [comment]
Can be done with #1492

**Comment by dixsie** [comment]
@Srisuk you won't see anything in the console unless you type something. try typing `ls`

**Comment by Su-kan** [comment]
Resolved by https://github.ibm.com/openbmc/webui-vue/pull/50
