### ISSUE TITLE
GUI : BMC Options - Tunable Sensor Stream Rate

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1497]
## SMEs
**BMC**: @spinler 

### User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

### InVision Prototype
- [ ] Invision prototype link

### Tasks
- [ ] Create design review story in webui-vue repo
- [ ] Send email to community sharing the design review story
- [ ] Post in story in the discord webui channel

### References
- eBMC Feature Item: 4.2.6
- [ ] Link to Discovery folder

### UX Flow / Interaction Requirements
- [ ] Feature breakdown

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by nicoleconser** [comment]
Tied to Telemetry data. This is establishing the rate at which to stream data to a remote  server (eg. 1x/sec or 1x/5 secs or 1x every min). This will benefit Justin's CRASSD tool which gathers all the telemetry statistics off a system. **Maury does not believe this is a GUI item.**

**Comment by nicoleconser** [comment]
@spinler Can you confirm that this is needed in the GUI?

**Comment by spinler** [comment]
I don't believe this is needed in the GUI.  The Redfish APIs to manipulate telemetry will probably be built into the tools that use it.

**Comment by derick-montague** [comment]
@gtmills @mzipse the description of this for backend in the tracking spread sheet suggests that this work **might** be to:

>  setting up which server we are streaming Power information to

If Matt is correct, I'd like to close this story and mark it as such in the tracking sheet.

**Comment by gtmills** [comment]
Yeah I think can be moved out of eBMC right?

**Comment by derick-montague** [comment]
Why did we reopen @nicoleconser? :)

**Comment by gtmills** [comment]
GA 2 for this, if not later. not for GA 1

**Comment by rfrandse** [comment]
tracking in jira
