### ISSUE TITLE
GUI : Singular Collect Service Data

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1517]
## SME
**BMC**: @ojayanth 
**RAS**: Justin Thaler
**PE**: Russel Young, Joe Mulholland

### Summary
This is a roll-up of Dumps (unclear yet which types, or if all Dump types), and is expected to live on the Server Overview page for quick access by customers. 

### User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

### InVision Prototype
- [ ] Invision prototype link

### Tasks
- [ ] Create design review story in webui-vue repo
- [ ] Send email to community sharing the design review story
- [ ] Post in story in the discord webui channel

### References
- eBMC Feature Item: 1.0.10
- [feature discovery document](https://ibm.box.com/s/0dzqw4lx3u5zgitr5yjgho72oo676st9)
- [Slack channel](https://ibm-systems-power.slack.com/archives/C014M9A0L56)

### UX Flow / Interaction Requirements
- [ ] Feature breakdown

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
This story needs a corresponding FED story.

**Comment by derick-montague** [comment]
Will not implement based on conversation with SME's.
