### ISSUE TITLE
GUI : FED : Server Control - Server LED

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#1590]
## Overview
Recreate page in Vue.js

## Tasks
- [ ] Verify if Redfish API is ready
- [ ] Add route and all route meta data
- [ ] Create page using page components
- [ ] Verify using consistent Save Form pattern
- [ ] Determine if new components or layout required and verify with design
- [ ] Include language translation

## As Is / To Be

Currently, the AngularJS Application has a Server LED page, create this page in Vue

![server-LED](https://user-images.githubusercontent.com/5455127/72462673-352dba00-3797-11ea-9590-1c489ea8a7b6.PNG)

**Comment by derick-montague** [comment]
Low Priority: https://ibm-systems-power.slack.com/archives/GQ8H06RC5/p1580500316015700

**Comment by derick-montague** [comment]
@gtmills - Can you help. What is the Redfish endpoint for Server LED?

**Comment by gtmills** [comment]
```
To GET / Set the system indicator LEDcurl -k https://{$bmc}/redfish/v1/Systems/system
....
"IndicatorLED": "Off",
..... 
```

**Comment by derick-montague** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/30854
