### ISSUE TITLE
GUI : FED : Update colors to remove unused colors

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1792]
## Overview
The color palette we are working with contains a large number of colors that we are not using within the application. 

## Tasks
- [x] Determine which colors are being used within the application
- [x] Remove any unused colors from the color maps
- [x] Update the Guidelines > Color documentation
- [ ] Discuss changes with design team

**Comment by derick-montague** [comment]
## Color Palette
![image](https://user-images.githubusercontent.com/1183515/75844164-d352ff00-5d9a-11ea-8e05-d309c15389e0.png)

![image](https://user-images.githubusercontent.com/1183515/75844219-f9789f00-5d9a-11ea-9fbb-03302827abb0.png)

**Comment by derick-montague** [comment]
## Buttons
![image](https://user-images.githubusercontent.com/1183515/75852148-f38db880-5db0-11ea-894e-58e5b9eda99e.png)

**Comment by derick-montague** [comment]
Resolved by:  https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29973
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29974
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29965
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29966

**Comment by derick-montague** [comment]
There are many changes there that need to be reviewed before I add reviewers in Gerrit.

**Comment by derick-montague** [comment]
I have removed some of the other associated gerrit reviews since the are related, but include a larger amount of work and should be tracked separately.
