### ISSUE TITLE
GUI : Design : Update Invision Projects

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1796]
## Description
There are screens that are in various states of completion spread through various release based projects. We should move any screens that are not completed (user tested and coded) to the Rainier project. It is hard for new team members joining to understand what is in progress and what is completed.

It will also be helpful if we update all the mockups to use the new header and navigation

## Tasks
- [x] Consolidate screens to one project (Rainier)
- [x] Update all screens to use the new header and navigation patterns
- [x] Bring the new designs from https://ibm.invisionapp.com/d/main#/projects/prototypes/15354657 into the project
