### ISSUE TITLE
GUI : FED : Primary Navigation color updates

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#1799]
## Overview
The navigation does not match the Invision mockup

## Tasks
- [ ] Update navigation active state to use dark background
- [ ] Update hover state to use default cursor (arrow) on active navigation items
- [ ] Remove use of Gray Sass tokens, e.g. `$gray-900`

**Comment by derick-montague** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/29887
