### ISSUE TITLE
GUI : Design : Network Settings (Revisit)

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2130]
## SME
**BMC**: ~~Ratan Gupta~~ @sunharis, Prashanth Katti
**PHYP**: Tom Burks
**Designer**: @derick-montague 

### Summary

The current design has been changed by the FED in the vue.js rewrite. There were issues with the existing design, along with API work that was not complete. This has led to some changes that need to:

1. Be reviewed
1. Possibly be redesigned

- [x] Review IPv4 layout for DHCP and Static
- [x] New design for IPv6 **(Not supported for GA1 [reference](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1614774937328200?thread_ts=1611923107.183900&cid=C0Q6TQP5Z))**
- [x] Gateway per interface
- [x] Review DHCP settings modal
- [x] ~~Review VMI or HyperVisor design~~
- [x] ~~VMI - virtual management interface is not an industry standard name. This is really the interface for the hypervisor. we need to test the naming with the community. [Slack conversation](https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1608060311254500?thread_ts=1608058690.251300&cid=GBVDZRCQK)~~
- [x] Do we need layout for both DHCP v4 and v6?

#### No DHCP server connected to the network
- **If there isn't a DHCP server connected to the network the system will crash if the user changes from static to DHCP.** 
- To keep the user from accidentally crashing a system, we display an error toast telling the user the DHCP settings were not saved. This is not intuitive and should be considered during the revisit.

### User Story
As a 
I need to 
in order to 

### InVision Prototype
- **Final Design**: https://ibm.invisionapp.com/share/72O1KJECWM4
- Iteration 3: https://ibm.invisionapp.com/share/V5O1KG1HPT4
- ~~Iteration 2: https://ibm.invisionapp.com/share/8RO1HLD7GHD~~
- ~~Iteration 1: https://ibm.invisionapp.com/share/WCO1CV7VNFD~~ - Archived

### Tasks
- [x] Create design review story in webui-vue repo
- [x] Add DHCP Settings
- [x] Review with team and users
- [x] Determine if DHCP settings are ready ([see slack conversation](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1627480541056300))
    - DHCPv4 are implemented (8/8/21) 
    - DHCPv6 may still need work
- [x] Verify if the DHCP settings (Use domain name, Use DNS servers, and Use NTP servers) are related between v4 and v6, e.g. If any of these are changed in DHCPv4, will that change the value in DHCPv6.
    - As of today, the answer is yes ([see slack conversation](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1627480541056300))
- [ ] Discuss IPv6 address state with engineering and support ([see box notes](https://ibm.box.com/s/n72o8ll46icat467eg6vhje9kmh0r42z))
- [ ] Determine if IPv6 has been implented on backend since addresses are included in the Redfish API
- [x] Send email to community sharing the design review story
- [ ] Post in story in the discord webui channel
- [ ] Move to FED

### References
- eBMC Feature Item 5.2: Network Settings (5.2.1 - 5.2.5)
- [Feature discovery folder](https://ibm.ent.box.com/folder/71322973079)
- [#bmc-vmi-config slack channel](https://ibm-systems-power.slack.com/archives/CMJNB7B7A)
- [Previous design screen captures](https://github.com/ibm-openbmc/dev/issues/936#issuecomment-501359407)
- [Redfish schema](http://redfish.dmtf.org/schemas/DSP2046_2020.3.html)

### UX Flow / Interaction Requirements
- [ ] Add the workflow (@derick-montague)

### cURL Commands and Redfish Response
- [ ] Add Redfish response

### DHCP
```
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"DHCPv4": {"DHCPEnabled": true}}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"DHCPv4": {"UseNTPServers": false}}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"DHCPv4": {"UseDomainName": false}}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0

curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"DHCPv4": {"UseDNSServers": false}}' https://$bmc/redfish/v1/Managers/bmc/EthernetInterfaces/eth0
```

### Notes
- https://github.com/ibm-openbmc/dev/issues/1515#issuecomment-599724795 - outlines some of the settings

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by nicoleconser** [comment]
Notes from [today's SEET meeting](https://ibm.ent.box.com/notes/688343093938) re: Service Flows: 

- Configuring Network Settings must be intuitive for legacy customers; comprehensive Knowledge Center documentation is critical. 
- Customers with legacy environments are used to seeing errors from their OS; will have to get used to logging in to the eBMC GUI instead.
- Standalone servers are now going to need to be connected to a network.

**Comment by derick-montague** [comment]
[Tom Burks reached out today in slack](https://ibm-systems-power.slack.com/archives/CLJD9CFLM/p1595359418002700) to let us know that there is a new HLDD for VMI and will include @nicoleconser and I the conversation.

**Comment by derick-montague** [comment]
[Jandra shared some info in November about VMI decisions and remaining discussion points](https://ibm-systems-power.slack.com/archives/CLJD9CFLM/p1574098992158400)

**Comment by derick-montague** [comment]
I believe this is the Redfish API for VMI

![image](https://user-images.githubusercontent.com/1183515/96734194-e5140180-137f-11eb-8798-68307e90c097.png)

**Comment by derick-montague** [comment]
Need to check with @ratagupt that all DHCP settings are in place. IPv6 may not be ready for first iteration.

**Comment by ParishrutB** [comment]
IPv6 not supported for GA1 [thread](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1614774937328200?thread_ts=1611923107.183900&cid=C0Q6TQP5Z)

**Comment by derick-montague** [comment]
@ParishrutB
[
In depth conversation in Discord starting on 3/03/21](https://discord.com/channels/775381525260664832/776550056391606352/816854612744208384)

Summary: If backend is in place it can be implemented by the community. It is low priority for us, but we should design for it when we start this story.

**Comment by derick-montague** [comment]
## VMI
In a meeting on 3/5/21 with Gunnar and Maury, it was suggested that this feature may not be needed. If we look at the design that was proposed by Jandra initially, all we were allowing to be changed was the VMI Host name. 

## DHCP Modal
In a meeting on 3/5/21 with Gunnar and Maury, it was stated that Ratan is working on the backend and that it should be ready soon.

**Comment by derick-montague** [comment]
VMI will not be needed for this application as all it allows is to send a change to the VMI host name. The determination this was not needed was in a sync meeting with Maury.

**Comment by derick-montague** [comment]
Setting this story as blocked until there is a clear understanding of how the back end works regarding DHCPv4 and DHCPv6. It is unclear if these are related and the Redfish API structure does not clearly indicate how the backend functions. 

For example, IPv4 default gateway determined by the first `gateway` property in the `IPv4StaticAddresses` array object.

```
    "IPv4StaticAddresses": [
        {
            "Address": "x.x.xx.xxx",
            "AddressOrigin": "Static",
            "Gateway": "x.x.xx.xxx",
            "SubnetMask": "255.255.255.0"
        }
    ],
```

Another example is `hostname`, which is included in each interface, but is applied to all interfaces if changed. Research in 2020 suggests that the DCHPv4 and DHCPv6 settings are similar to `hostname` and are global settings that apply to all interfaces. Understanding this will make help to inform the usability of the UI and without this understanding, the update to the Network settings is blocked.

**Comment by derick-montague** [comment]
> Setting this story as blocked until there is a clear understanding of how the back end works regarding DHCPv4 and DHCPv6. It is unclear if these are related and the Redfish API structure does not clearly indicate how the backend functions.

The answer for how DHCP works ([discussion in slack](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1627480541056300)

1. DHCP settings, `UseNTPServers`, `UseDNSServers`, `UseDomainName` are global settings even though they are saved in the the `DHCPv4` and `DHCPv6` objects.

```
"DHCPv4": {
        "DHCPEnabled": false,
        "UseDNSServers": true,
        "UseDomainName": true,
        "UseNTPServers": true
    },
    "DHCPv6": {
        "OperatingMode": "Stateful",
        "UseDNSServers": true,
        "UseDomainName": true,
        "UseNTPServers": true
    },
```
2. These settings will be applied to any interface that the `DHCPEnabled`  property is set to true or `OperatingMode` property in set to `Stateful`
    - This is true for DHCPv4 and DHCPv6. However, there are some questions about DHCPv6 on the backend.

**Comment by derick-montague** [comment]
The structure of the Redfish API for interfaces and keeping the default gateway in each static IPv4 address is a significant issue to work around. It was [discussed on the Redfish forum back in 2019](https://redfishforum.com/thread/218/ip-address-default-gateway), but it looks like there weren't any responses to Ratan.

**Comment by derick-montague** [comment]
Most users were confused by the ability to add multiple static IP addresses since ASMI v1 only allows for one IP address per interface. The users also expected that DHCP server information would only be available `after` enabling DHCP on the interface. 

I have asked for [clarification from the engineering team in this slack thread](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1631113498355900).

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/48197
