### ISSUE TITLE
GUI : eBMC Hardware Status and VPD

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2210]
## SMEs
**BMC**: @gtmills, @santoshpuranik 
**RAS**: Michael Muller (CPU, Memory, HMC management), Kenisha Patel (physical labels, VPD, changes needed with part identification, etc), Dan Henderson (CPU & error detection expert, Hostboot, PRD), George Ahrens (both Dan & George are SBEs on our high-end box), Zane Shelley & Marc Gollub (Memory experts) (for more info on each role, see our [Problem Statement research](https://ibm.box.com/s/k3f9kzm527ajooymfrxz46sas93sqtnz) doc) 
**PE**: Russ Young, Joe Mulholland

### Important conversations
- Internal discussion on layout of expansion rows: https://ibm-systems-power.slack.com/archives/GBVDZRCQK/p1618498301092600

### Important documents
VPD API information and sorting: https://ibm.ent.box.com/notes/790802538332

### Summary
Part of the update to the Hardware Status page is to include VPD from ASMI. ~~There has been some conversation users are interested in being able to quickly identify the the hardware hierarchy / architecture. If there is a critical event log associated with a hardware failure, linking that from the hardware inventory to the event log would be a great enhancement if it is possible~~.

It is less likely that we are going to try to enhance the experience if the goal of the project is parity with ASMI. We will need to base our design on the Redfish API without specification enhancement unless the engineering team has already started the work with the DMTF group.

### End Users
- Paul (Product Engineer)
- Tricia (Power Sys Admin)
- Noah (Junior Sys Admin w/o HMC) 

### User Story

- As a PE/SSR, I need to be able to perform detailed analysis related to a hardware fault, so that I can point out which hardware components need to be serviced/replaced.
- As an SSR, I need to reference detailed information about one or more components, where they are installed, and switch on required LED indicators before carrying out a replacement.

### InVision Prototype
**Final**
- **Final prototype** https://ibm.invisionapp.com/share/FSO15NYNE9P
- **Expansion row details** https://ibm.invisionapp.com/share/52O15NX9FA7

**Iterations**
- **Lofi test** https://ibm.invisionapp.com/share/RHO0ZVRV5JU
-  **Iteration 3** https://ibm.invisionapp.com/share/QCO0YR7SHX9
-  **Iteration 2** https://ibm.invisionapp.com/share/39O0YCKCM5U
- **Iteration 1** https://ibm.invisionapp.com/share/UGO0XTXMNKD

### Tasks
- [x] Create design review story in webui-vue repo
- [x] Discovery research 
- [x] SME interviews 
- [x] User interviews 
- [x] Lo-fi-designs
- [x] Lofi tests 
- [x] Hi-fi designs 
- [x] Send email to community sharing the design review story
- [ ] Post in story in the discord webui channel

#### Tasks needed to remove blocker 
- [ ] Set up time in Design exchange meeting
    - [ ] Determine which properties are missing from Redfish that need to be supported
    - [ ] Determine best way to work with SME
    - [ ] FED to work on each FRU with design owner to assure consistency in layout

### References/Resources
- [Feature discovery](https://ibm.ent.box.com/folder/106564446310)
- User research notes*: 
    - [Slack conversation about correlation of logs and hardware status](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1588264231220300)
- [Redfish Mockup](https://redfish.dmtf.org/redfish/mockups/v1/950)
- [Internal Feedback Forum - Slack posts
](https://ibm.ent.box.com/notes/771513279364?s=c2gk0fv804kg72g8doiqcnv2x1m6t1r8)
-  Discovery research findings: [link](https://app.mural.co/t/ibmpower1831/m/ibmpower1831/1612954253881/1a975e0cba1018635707be0e646441d328dbb149)

**Comment by derick-montague** [comment]
In OpenBMC demo today, it was discussed that the inventory was primed with every possible FRU. A FRU without VPD will only include `Location Code` and `Type`

**Comment by nicoleconser** [comment]
From Gunnar: The HW inventory/status page should include the following ASMI menu items: **Enclosure Indicators** and **Indicators by Location code**. "These represent individual FRUs, so would be on the HW Inventory page. Vishwa is driving this."

**Comment by derick-montague** [comment]
> Part of the update to the Hardware Status page is to include VPD from ASMI. There has been some conversation users are interested in being able to quickly identify the the hardware hierarchy / architecture. If there is a critical event log associated with a hardware failure, linking that from the hardware inventory to the event log would be a great enhancement if it is possible.

This description listed above is a nice to have. It is not likely that we will make any big changes to the Hardware Inventory unless @gtmills knows of some specific user needs that should be addressed.

**Comment by gtmills** [comment]
Justin had mentioned a hierarchical presentation.
Might be worth asking users about, but I would say not critical.

**Comment by derick-montague** [comment]
FYI -> IBM is the only company LocationCode and `CCIN`, which is called model in Redfish. We may want to follow the Redfish naming.

**Comment by derick-montague** [comment]
> FYI -> IBM is the only company `LocationCode` and `CCIN#`, which is called `Model` in Redfish.
> 
> We may want to follow the Redfish naming and use `Model` instead of `CCIN`. Also, because LocationCode is IBM only, if we make that a table header, it has to be dynamic since no other company will have that value in the table.

**Correction**: There is a Redfish property we can use for LocationCode. It is called `Part Location ServiceLabel` in the Redfish API.

**Comment by derick-montague** [comment]
I added @Srisuk to help Priyanka. If there is a conflict and we need a different team member to collaborate, please bring up in daily standup.

**Comment by derick-montague** [comment]
The current state of the backend requires that we schedule time in @bradbishop design exchange meeting. @derick-montague will we responsible for setting up time in the meeting.

**Comment by derick-montague** [comment]
Implementation will be done per FRU in the associated stories blocking

**Comment by derick-montague** [comment]
Moved into current sprint since design is working with the FEDs to create the layout for VPD.
