### ISSUE TITLE
GUI : Overview Layout

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2211]
## SME
NA

### Use Case
- As an OpenBMC admin, I need to be able to quickly find pertinent information when I first login to the OpenBMC GUI. 

### InVision Prototype
- Upstream https://ibm.invisionapp.com/share/C2O1E629BRS#/screens/320050499
- Downstream https://ibm.invisionapp.com/share/C2O1E629BRS#/screens/320050299

### References
- eBMC Feature Item: 4.7
- Discovery doc: https://ibm.ent.box.com/notes/827239298636
- [Link to Discovery folder](https://ibm.ent.box.com/notes/768289701177)

### UX Flow / Interaction Requirements
- Community version: Remove CE login, Access Key expiration date. Button text for post codes: "View real-time post codes"
- Community version: Button text for post codes: "View real-time progress codes"
- Each "View more" buttons links to its corresponding page, e.g. For events logs, "View more" links to Event Logs page. 
- Power information: Power saver mode - show Disabled or chosen option if enabled. Idle power saver - show Disabled or "threshold to enter - threshold to exit" if enabled. Power cap - Show Disabled or setting value if enabled.

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

______________________

### Assumptions
- [ ] Showing the system name to the user prominently is critical for the user to identify which system they are using/on. _The system name will be part of the header (#1292), but the user will need a place to edit the system name. It is not clear if this is the right page, but in AngularJS, we allowed the user to edit directly on this screen._
- [ ] BMC Date and Time is important to see since they can often drift.
- [ ] Users need to see only a few of the latest error messages. Troubleshooting will be conducted on the Events logs page
- [ ] BMC Firmware version  important to quickly find for sharing with IBM to quickly troubleshoot problems
- [ ] Server information section is important to quickly find for sharing with IBM to quickly troubleshoot problems
- [ ] Network settings is important to be able to see and quickly access when setting up a server.
- [ ] Power usage information is important to see for troubleshooting a system issue
- [ ] Singular collect data button may need to live on this page. #1517 
- [ ] Consider the application header improvement research with this story #2424 

### Questions
- [ ] Why is the Serial over LAN quick link so important that it needs to be on the Overview page?
- [x] Why is Server LED toggle so important that it needs to be on the Overview page?
   - Extremely users need to quickly identify the system in the rack. [DM]
- [ ] Should there be a quick ink to the Power Cap settings page?
- [ ] Server information is only found on the overview page, so should it be more prominent?
- [x] Should there be a quick link to the Firmware Update page?
    - Not used often enough to warrant this on the overview page [DM]
- [ ] How does the current layout scale to accommodate that possibility?
- [ ] Should the system name, if located on the Overview page, be editable on the overview page?

### Current Layout
The current layout of the overview page is cluttered and not easily scannable.

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/a887f4d6-dec9-4278-bf8a-2b79483b0e35)

**Comment by ben-bacon** [comment]
> Why is the Serial over LAN quick link so important that it needs to be on the Overview page? 
  - Definitely appropriate Q, can send this Q as an email/slack
> Why is Server LED toggle so important that it needs to be on the Overview page?
  - Not a cumbersome element, probably adds some ease of use, appropriate Q but I'd say low priority.
> Should there be a quick ink to the Power Cap settings page?
  - Definitely appropriate Q, can send this Q as an email/slack
> Server information is only found on the overview page, so should it be more prominent?
  - Feasable, will keep this suggestion in mind
> Should there be a quick link to the Firmware Update page?
  - Definitely appropriate Q, can send this Q as an email/slack
> How possible is it for the system to have multiple network interfaces? How does the current layout scale to accommodate that possibility?
  - Definitely appropriate Q, can send this Q as an email/slack, highest priority

I'll reformat these questions a bit and sync up with Nicole on them

**Comment by derick-montague** [comment]
@nicoleconser - Do you have any ideas on how/when we can get some user feedback on this?

**Comment by nicoleconser** [comment]
Another assumption you may want to add to this description and/or your discovery doc @ParishrutB: 

**System name** should be editable from this screen, as it was in the Angular app. FYI we are also considering bringing _System name_ to the Header, as it was in the Angular app. 

It was determined during a GUI workgroup meeting that **Hostname** is not important enough information to live in the Header, but _Hostname_ is different from _System name_. 

Recently, a customer (very randomly - we did not ask, and we were not focusing on the header) pointed out that _System name_ is missing from the header in our Vue prototypes. She stated that _System name_ is useful to see at all times, because it gives you a sense of "where I am" (i.e. I have 1000s of servers in my data center - and 12 GUI tabs open in my browser - which server am I on?).

**Comment by derick-montague** [comment]
>  She stated that System name is useful to see at all times, because it gives you a sense of "where I am" (i.e. I have 1000s of servers in my data center - and 12 GUI tabs open in my browser - which server am I on?).

That is a fantastic insight! I was going to suggest something other than the header, specifically, the title of each page. This would be interesting since the user could look to their tab to see the server name. The only concern is the the system name length. Here is an example though...

![image](https://user-images.githubusercontent.com/1183515/88845118-4ecda680-d1a9-11ea-81fe-fa4faf0cb05d.png)

**Comment by ParishrutB** [comment]
Chat conversation regarding system name: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1595976814152100

**Comment by derick-montague** [comment]
Moving this story to Sprint + 1. We can review with community in Gerrit. I don't see a reason for this not to be complete.

**Comment by derick-montague** [comment]
@dixsie for Downstream, I would like to make the following changes to the design. Please let me know if  you have any concerns.

![image](https://user-images.githubusercontent.com/1183515/129292903-6306d284-6796-410f-9d90-496179923b93.png)

**Comment by dixsie** [comment]
Upstream resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/46511

Changes were made to the network settings section - only displaying the hostname, link status and first IP address of the first interface
![Screen Shot 2021-09-02 at 4.02.06 PM.png](https://images.zenhubusercontent.com/5c969c26c2488c52df50b7eb/00fea456-5175-404d-90b0-97d32a2c6278)

### TODO:
- [ ] **Power mode** should be updated on overview page as part of #1485
- [ ] **Power idle** should be updated on overview page as part of  #1487
