### ISSUE TITLE
GUI : FED : Update icons in tables and header

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2379]
## Tasks
- [ ] Replace error with misuse icon
- [ ] Replace export with document-export icon
- [ ] Update Health icon in header to use misuse icon instead of error icon

![image](https://user-images.githubusercontent.com/52676199/86368014-53527e00-bc42-11ea-910a-c9cca269120d.png)

_Originally posted by @ben-bacon in https://github.com/ibm-openbmc/dev/issues/580#issuecomment-653022862_

**Comment by ben-bacon** [comment]
@Srisuk please ignore the warning icon have on the mockup, I was mistaken. We are leaving that one as is, "warning filled" with the round circle with exclamation mark.

**Comment by Srisuk** [comment]
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34892

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/34892 merged
