### ISSUE TITLE
GUI : FED : PageSection component margins

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2497]
## Overview
Increase the global margin(bottom) size for for the PageSection component. Consider small-screen layouts and current util classes that have already been used to modify space. 
Verify changes with @ben-bacon 

## Tasks
- [ ] Use utility class to set margin on the component
- [ ] Verify UI changes on all pages (some pages have custom styles in the SFC style block)

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by derick-montague** [comment]
This would be a good opportunity for using a utility class.

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36055

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/36055 merged
