### ISSUE TITLE
GUI : FED : Update table filter action "Clear all" button to match style guide

### ISSUE THREAD

**Issue by dixsie** [ibm-openbmc/dev#2503]
## Overview
- [ ] When clear all button is :active, text is no longer visible 

<img width="186" alt="Screen Shot 2020-08-11 at 3 14 53 PM" src="https://user-images.githubusercontent.com/26472611/89945304-c3abd200-dbe6-11ea-9699-74e3e6e269ae.png">
<img width="195" alt="Screen Shot 2020-08-11 at 3 08 34 PM" src="https://user-images.githubusercontent.com/26472611/89945733-6cf2c800-dbe7-11ea-8e0c-2713bb5afa67.png">

## Tasks
- [ ] Validate this is resolved with @SurenNeware work on buttons
- [ ] If not resolved, fix the issue

## UX Flow / Interaction Requirements
- [ ] Text should be visible when button is clicked
- [ ] Update clear all button to use "ghost button" style

## InVision
Style guide: https://ibm.invisionapp.com/share/U9O039T4Q6E#/screens/319613166

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

**Comment by dixsie** [comment]
@ben-bacon should the clear all button on tale filters be primary buttons or ghost buttons?

**Comment by ben-bacon** [comment]
@dixsie Ghost please!

**Comment by derick-montague** [comment]
@SurenNeware - Please close this story if resolved by #2332

**Comment by derick-montague** [comment]
@SurenNeware verified this issue is resolved in #2332.

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35981

**Comment by rfrandse** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/35981 merged
