### ISSUE TITLE
eBMC GUI : Vue 3 migration

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2681]
## Tasks (Delete when completed)
- [ ] Add the milestone
- [ ] Add to the Epic pipeline
- [ ] Create as Epic
- [ ] Add Research, Design, and FED stories to the Epic
   - Create placeholder stories for each design / fed stage if they don't exist

## Summary
- [ ] Add brief summary of the overall Epic
    - Is this part of a new or existing Information Architecture
    - Is this just a wrapper for the stories created for each design / fed stages

## References/Resources
- [ ] Add eBMC Feature Item <add item number>
- [ ] Add feature discovery folder (create if doesn't exist)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
tracking in jira
