### ISSUE TITLE
GUI : FED : Remove Overview sections in Guidelines and Coding Standards

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2696]
## Overview
An overview of each section is not needed for the Guidelines and Coding Standards sections.

## Tasks
- [ ] Remove the pages from the config file
- [ ] Delete the readme.md files from the Guidelines and Coding Standards directory

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

## Notes
N/A

### Testing Guidelines
- [ ] Run documentation locally
- [ ] Verify sections render and that the overview pages are not listed in the navigation

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
N/A

### Accessibility Tests
N/A

**Comment by dixsie** [comment]
resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37667
