### ISSUE TITLE
GUI : FED : Resolve custom-event-name-casing lint warnings

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2710]
## Overview
We have not been consistent in our naming of custom events. The vue best practices calls for using kebab case. This story story will update all the custom event names that are not in kebab case. 

Our goal is consistency, so rather than adding any special patterns, we want to comply with the guidelines. An example is:

**Change Examples**: 
- `action:eventName` to `action-event-name`
- `action::eventName to `action-event-name`
- `actionEventName` to `action-event-name`

### Tasks
- [ ] Update the code to fix the warnings
- [ ] Remove the rule at line 19 of the `.eslintrc.js` file  (`'vue/custom-event-name-casing': ['warn'],`) 

### Rule details
https://eslint.org/docs/rules/no-prototype-builtins

### Rule Documentation
- https://eslint.vuejs.org/rules/custom-event-name-casing.html

### Rule violations
Run: `npm run lint` in the project and find and address all of these errors for `(vue/custom-event-name-casing)`

```

warning: Custom event name 'toggle:navigation' must be kebab-case (vue/custom-event-name-casing) at src/components/AppHeader/AppHeader.vue:180:24:
  178 |     },
  179 |     toggleNavigation() {
> 180 |       this.$root.$emit('toggle:navigation');
      |                        ^
  181 |     }
  182 |   }
  183 | };


warning: Custom event name 'change:isNavigationOpen' must be kebab-case (vue/custom-event-name-casing) at src/components/AppNavigation/AppNavigation.vue:74:24:
  72 |     },
  73 |     isNavigationOpen: function (isNavigationOpen) {
> 74 |       this.$root.$emit('change:isNavigationOpen', isNavigationOpen);
     |                        ^
  75 |     }
  76 |   },
  77 |   mounted() {


warning: Custom event name 'changeSearch' must be kebab-case (vue/custom-event-name-casing) at src/components/Global/Search.vue:58:18:
  56 |   methods: {
  57 |     onChangeInput() {
> 58 |       this.$emit('changeSearch', this.filter);
     |                  ^
  59 |     },
  60 |     onClearSearch() {
  61 |       this.filter = '';


warning: Custom event name 'clearSearch' must be kebab-case (vue/custom-event-name-casing) at src/components/Global/Search.vue:62:18:
  60 |     onClearSearch() {
  61 |       this.filter = '';
> 62 |       this.$emit('clearSearch');
     |                  ^
  63 |       this.$refs.searchInput.focus();
  64 |     }
  65 |   }


warning: Custom event name 'filterChange' must be kebab-case (vue/custom-event-name-casing) at src/components/Global/TableFilter.vue:109:18:
  107 |     },
  108 |     emitChange() {
> 109 |       this.$emit('filterChange', {
      |                  ^
  110 |         activeFilters: this.activeFilters
  111 |       });
  112 |     },


warning: Custom event name 'click:tableAction' must be kebab-case (vue/custom-event-name-casing) at src/components/Global/TableRowAction.vue:22:21:
  20 |       :title="title"
  21 |       :disabled="!enabled"
> 22 |       @click="$emit('click:tableAction', value)"
     |                     ^
  23 |     >
  24 |       <slot name="icon">
  25 |         {{ title }}


warning: Custom event name 'batchAction' must be kebab-case (vue/custom-event-name-casing) at src/components/Global/TableToolbar.vue:15:27:
  13 |             variant="primary"
  14 |             class="d-block"
> 15 |             @click="$emit('batchAction', action.value)"
     |                           ^
  16 |           >
  17 |             {{ action.label }}
  18 |           </b-button>


warning: Custom event name 'clearSelected' must be kebab-case (vue/custom-event-name-casing) at src/components/Global/TableToolbar.vue:23:27:
  21 |             variant="secondary"
  22 |             class="d-block"
> 23 |             @click="$emit('clearSelected')"
     |                           ^
  24 |           >
  25 |             {{ $t('global.action.cancel') }}
  26 |           </b-button>


warning: Custom event name 'loader::start' must be kebab-case (vue/custom-event-name-casing) at src/components/Mixins/LoadingBarMixin.js:9:24:
   7 |   methods: {
   8 |     startLoader() {
>  9 |       this.$root.$emit('loader::start');
     |                        ^
  10 |       this.loading = true;
  11 |     },
  12 |     endLoader() {


warning: Custom event name 'loader::end' must be kebab-case (vue/custom-event-name-casing) at src/components/Mixins/LoadingBarMixin.js:13:24:
  11 |     },
  12 |     endLoader() {
> 13 |       this.$root.$emit('loader::end');
     |                        ^
  14 |       this.loading = false;
  15 |     },
  16 |     hideLoader() {


warning: Custom event name 'loader::hide' must be kebab-case (vue/custom-event-name-casing) at src/components/Mixins/LoadingBarMixin.js:17:24:
  15 |     },
  16 |     hideLoader() {
> 17 |       this.$root.$emit('loader::hide');
     |                        ^
  18 |     }
  19 |   }
  20 | };


warning: Custom event name 'serverPowerOperations::bootSettings::complete' must be kebab-case (vue/custom-event-name-casing) at src/views/Control/ServerPowerOperations/BootSettings.vue:102:24:
  100 |       this.$store.dispatch('hostBootSettings/getTpmPolicy')
  101 |     ]).finally(() =>
> 102 |       this.$root.$emit('serverPowerOperations::bootSettings::complete')
      |                        ^
  103 |     );
  104 |   },
  105 |   methods: {


warning: Custom event name 'hardwareStatus::bmcManager::complete' must be kebab-case (vue/custom-event-name-casing) at src/views/Health/HardwareStatus/HardwareStatusTableBmcManager.vue:196:24:
  194 |     this.$store.dispatch('bmc/getBmcInfo').finally(() => {
  195 |       // Emit initial data fetch complete to parent component
> 196 |       this.$root.$emit('hardwareStatus::bmcManager::complete');
      |                        ^
  197 |     });
  198 |   }
  199 | };


warning: Custom event name 'hardwareStatus::chassis::complete' must be kebab-case (vue/custom-event-name-casing) at src/views/Health/HardwareStatus/HardwareStatusTableChassis.vue:118:24:
  116 |     this.$store.dispatch('chassis/getChassisInfo').finally(() => {
  117 |       // Emit initial data fetch complete to parent component
> 118 |       this.$root.$emit('hardwareStatus::chassis::complete');
      |                        ^
  119 |     });
  120 |   }
  121 | };


warning: Custom event name 'hardwareStatus::dimmSlot::complete' must be kebab-case (vue/custom-event-name-casing) at src/views/Health/HardwareStatus/HardwareStatusTableDimmSlot.vue:139:24:
  137 |     this.$store.dispatch('memory/getDimms').finally(() => {
  138 |       // Emit initial data fetch complete to parent component
> 139 |       this.$root.$emit('hardwareStatus::dimmSlot::complete');
      |                        ^
  140 |     });
  141 |   },
  142 |   methods: {


warning: Custom event name 'hardwareStatus::fans::complete' must be kebab-case (vue/custom-event-name-casing) at src/views/Health/HardwareStatus/HardwareStatusTableFans.vue:138:24:
  136 |     this.$store.dispatch('fan/getFanInfo').finally(() => {
  137 |       // Emit initial data fetch complete to parent component
> 138 |       this.$root.$emit('hardwareStatus::fans::complete');
      |                        ^
  139 |     });
  140 |   },
  141 |   methods: {


warning: Custom event name 'hardwareStatus::powerSupplies::complete' must be kebab-case (vue/custom-event-name-casing) at src/views/Health/HardwareStatus/HardwareStatusTablePowerSupplies.vue:161:24:
  159 |     this.$store.dispatch('powerSupply/getPowerSupply').finally(() => {
  160 |       // Emit initial data fetch complete to parent component
> 161 |       this.$root.$emit('hardwareStatus::powerSupplies::complete');
      |                        ^
  162 |     });
  163 |   },
  164 |   methods: {


warning: Custom event name 'hardwareStatus::processors::complete' must be kebab-case (vue/custom-event-name-casing) at src/views/Health/HardwareStatus/HardwareStatusTableProcessors.vue:168:24:
  166 |     this.$store.dispatch('processors/getProcessorsInfo').finally(() => {
  167 |       // Emit initial data fetch complete to parent component
> 168 |       this.$root.$emit('hardwareStatus::processors::complete');
      |                        ^
  169 |     });
  170 |   },
  171 |   methods: {


warning: Custom event name 'hardwareStatus::system::complete' must be kebab-case (vue/custom-event-name-casing) at src/views/Health/HardwareStatus/HardwareStatusTableStystem.vue:130:24:
  128 |     this.$store.dispatch('system/getSystem').finally(() => {
  129 |       // Emit initial data fetch complete to parent component
> 130 |       this.$root.$emit('hardwareStatus::system::complete');
      |                        ^
  131 |     });
  132 |   }
  133 | };


warning: Custom event name 'overview::events::complete' must be kebab-case (vue/custom-event-name-casing) at src/views/Overview/OverviewEvents.vue:74:24:
  72 |   created() {
  73 |     this.$store.dispatch('eventLog/getEventLogData').finally(() => {
> 74 |       this.$root.$emit('overview::events::complete');
     |                        ^
  75 |     });
  76 |   }
  77 | };


warning: Custom event name 'overview::network::complete' must be kebab-case (vue/custom-event-name-casing) at src/views/Overview/OverviewNetwork.vue:53:24:
  51 |   created() {
  52 |     this.$store.dispatch('networkSettings/getEthernetData').finally(() => {
> 53 |       this.$root.$emit('overview::network::complete');
     |                        ^
  54 |     });
  55 |   }
  56 | };


warning: Custom event name 'overview::quicklinks::complete' must be kebab-case (vue/custom-event-name-casing) at src/views/Overview/OverviewQuickLinks.vue:86:24:
  84 |       this.$store.dispatch('serverLed/getIndicatorValue')
  85 |     ]).finally(() => {
> 86 |       this.$root.$emit('overview::quicklinks::complete');
     |                        ^
  87 |     });
  88 |   },
  89 |   methods: {


warning: Custom event name 'change:isNavigationOpen' must be kebab-case (vue/custom-event-name-casing) at tests/unit/AppHeader.spec.js:61:26:
  59 |   it('change:isNavigationOpen event should set isNavigationOpen prop to false', async () => {
  60 |     const rootWrapper = createWrapper(wrapper.vm.$root);
> 61 |     rootWrapper.vm.$emit('change:isNavigationOpen', false);
     |                          ^
  62 |     await rootWrapper.vm.$nextTick();
  63 |     expect(wrapper.vm.isNavigationOpen).toEqual(false);
  64 |   });


warning: Custom event name 'toggle:navigation' must be kebab-case (vue/custom-event-name-casing) at tests/unit/AppNavigation.spec.js:40:26:
  38 |     const rootWrapper = createWrapper(wrapper.vm.$root);
  39 |     wrapper.vm.isNavigationOpen = false;
> 40 |     rootWrapper.vm.$emit('toggle:navigation');
     |                          ^
  41 |     expect(wrapper.vm.isNavigationOpen).toBe(true);
  42 |     rootWrapper.vm.$emit('toggle:navigation');
  43 |     expect(wrapper.vm.isNavigationOpen).toBe(false);


warning: Custom event name 'toggle:navigation' must be kebab-case (vue/custom-event-name-casing) at tests/unit/AppNavigation.spec.js:42:26:
  40 |     rootWrapper.vm.$emit('toggle:navigation');
  41 |     expect(wrapper.vm.isNavigationOpen).toBe(true);
> 42 |     rootWrapper.vm.$emit('toggle:navigation');
     |                          ^
  43 |     expect(wrapper.vm.isNavigationOpen).toBe(false);
  44 |   });
  45 | });
```

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Ran `npm run lint` and all `custom-event-name-casing` errors have been resolved
- [ ] Ran `npm run serve` and verified all events changed have been fully tested
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
N/A

**Comment by derick-montague** [comment]
@Srisuk - Please create a branch from this gerrit commit: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37578

**Comment by derick-montague** [comment]
@Srisuk - After pulling that repo, be sure to run `npm ci` to update all the packages or when linting is run, it will revert all the updated files that don't meet the new linting rules. :)

**Comment by Srisuk** [comment]
Resolve by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37776
