### ISSUE TITLE
GUI : FED : Resolve no-prototype-builtins lint warnings

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2711]
## Overview
Updating the linting rules  to follow best practices resulted in errors in how we are testing if an object has it's own property. In the short term, we added an override to change the error to a warning. The goal of this story is to resolve all the warning messages.

### Tasks
- [ ] Update the code to fix the warnings
- [ ] Remove the rule at line 8 of the `.eslintrc.js` file  (`no-prototype-builtins': 'warn',`) 

### Rule details
https://eslint.org/docs/rules/no-prototype-builtins

### Warning messages
```
warning: Do not access Object.prototype method 'hasOwnProperty' from target object (no-prototype-builtins) at src/components/Global/TableToolbar.vue:47:20:
  45 |         return prop.every((action) => {
  46 |           return (
> 47 |             action.hasOwnProperty('value') && action.hasOwnProperty('label')
     |                    ^
  48 |           );
  49 |         });
  50 |       }


warning: Do not access Object.prototype method 'hasOwnProperty' from target object (no-prototype-builtins) at src/components/Global/TableToolbar.vue:47:54:
  45 |         return prop.every((action) => {
  46 |           return (
> 47 |             action.hasOwnProperty('value') && action.hasOwnProperty('label')
     |                                                      ^
  48 |           );
  49 |         });
  50 |       }


warning: Do not access Object.prototype method 'hasOwnProperty' from target object (no-prototype-builtins) at src/views/AccessControl/Ldap/ModalAddRoleGroup.vue:95:16:
  93 |         if (prop === null) return true;
  94 |         return (
> 95 |           prop.hasOwnProperty('groupName') &&
     |                ^
  96 |           prop.hasOwnProperty('groupPrivilege')
  97 |         );
  98 |       }


warning: Do not access Object.prototype method 'hasOwnProperty' from target object (no-prototype-builtins) at src/views/AccessControl/Ldap/ModalAddRoleGroup.vue:96:16:
  94 |         return (
  95 |           prop.hasOwnProperty('groupName') &&
> 96 |           prop.hasOwnProperty('groupPrivilege')
     |                ^
  97 |         );
  98 |       }
  99 |     }


warning: Do not access Object.prototype method 'hasOwnProperty' from target object (no-prototype-builtins) at src/views/AccessControl/SslCertificates/ModalUploadCertificate.vue:86:16:
  84 |         if (prop === null) return true;
  85 |         return (
> 86 |           prop.hasOwnProperty('type') && prop.hasOwnProperty('certificate')
     |                ^
  87 |         );
  88 |       }
  89 |     }


warning: Do not access Object.prototype method 'hasOwnProperty' from target object (no-prototype-builtins) at src/views/AccessControl/SslCertificates/ModalUploadCertificate.vue:86:47:
  84 |         if (prop === null) return true;
  85 |         return (
> 86 |           prop.hasOwnProperty('type') && prop.hasOwnProperty('certificate')
     |                                               ^
  87 |         );
  88 |       }
  89 |     }
```

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Ran `npm run serve` and tested the updated views
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
N/A

**Comment by derick-montague** [comment]
Please branch off of this Gerrit patchset: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37578

**Comment by yoshiemuranaka** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37811
