### ISSUE TITLE
GUI : FED : Resolve vue/no-unused-vars lint warnings

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2712]
## Overview
Updating the linting rules  to follow best practices resulted in errors for creating variables and not using them. The goal of this story is to resolve these warning messages.

### Tasks
- [ ] Update the code to fix the warnings
- [ ] Remove the rule at line 20 of the `.eslintrc.js` file  (`'vue/no-unused-vars': ['warn']`) 

### Rule details
https://eslint.org/docs/rules/no-prototype-builtins

### Warning messages
```
warning: 'ok' is defined but never used (vue/no-unused-vars) at src/views/AccessControl/LocalUserManagement/ModalSettings.vue:107:32:
  105 |       </b-container>
  106 |     </b-form>
> 107 |     <template #modal-footer="{ ok, cancel }">
      |                                ^
  108 |       <b-button
  109 |         variant="secondary"
  110 |         data-test-id="localUserManagement-button-cancel"


warning: 'ok' is defined but never used (vue/no-unused-vars) at src/views/AccessControl/LocalUserManagement/ModalUser.vue:203:32:
  201 |       </b-container>
  202 |     </b-form>
> 203 |     <template #modal-footer="{ ok, cancel }">
      |                                ^
  204 |       <b-button
  205 |         variant="secondary"
  206 |         data-test-id="localUserManagement-button-cancel"
```

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Ran `npm run serve` and tested the updated views
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
N/A

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37812
