### ISSUE TITLE
GUI : FED : Resolve vue/no-lone-template lint warning message

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2713]
## Overview
Updating the linting rules  to follow best practices resulted in errors for creating variables and not using them. The goal of this story is to resolve these warning messages. Use the rule details page to determine if this rule should be applied in our environment.

### Tasks
- [ ] Update the code to fix the warning

### Rule details
https://eslint.vuejs.org/rules/no-lone-template.html

### Warning messages
```
warning: `<template>` require directive (vue/no-lone-template) at src/views/Control/SerialOverLan/SerialOverLanConsole.vue:3:5:
  1 | <template>
  2 |   <div :class="isFullWindow ? 'full-window-container' : 'terminal-container'">
> 3 |     <template>
    |     ^
  4 |       <b-row class="d-flex">
  5 |         <b-col class="d-flex flex-column justify-content-end">
  6 |           <dl class="mb-2" sm="6" md="6">
```

## UX Flow / Interaction Requirements
N/A

## Final Invision Mockup
N/A

## cURL Commands
N/A

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Ran `npm run serve` and tested the updated view
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
N/A

**Comment by yoshiemuranaka** [comment]
This is also a breaking change coming with Vue 3 #2723

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37878

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/37878
