### ISSUE TITLE
GUI : FED : Add system asset tag in app header

### ISSUE THREAD

**Issue by yoshiemuranaka** [ibm-openbmc/dev#2780]
## Overview
Add system name in app header. Should be displayed as mocked in design. The system name should also appear in the page title

### Tasks Breakdown
- [ ] Add system name in the application header
- [ ] Add the system name prior to the page name in the page title

## Final Invision Mockup
https://ibm.invisionapp.com/share/XCO0EVSTZMJ

### Screen capture
![image](https://user-images.githubusercontent.com/1183515/101675600-a6193880-3a1f-11eb-906d-ef9233e9052a.png)

## cURL Commands
```
curl -k -X PATCH -d '{"AssetTag": "Paramo"}' https://${bmc}/redfish/v1/Systems/system/
```

## Notes
- Editing system name will be worked on separately
- Related design story  #1292 
- https://github.com/ibm-openbmc/dev/issues/1292#issuecomment-689281253

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

## Screenshot

<img width="1670" alt="Screen Shot 2020-12-01 at 10 49 42 AM" src="https://user-images.githubusercontent.com/8097306/100783768-0de9d680-33c3-11eb-96b3-0815eafdf5d6.png">

**Comment by Srisuk** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/38907
