### ISSUE TITLE
GUI : FED : Update linting and code formatting node packages

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2848]
## Overview
Update the following node packages to their latest release. None of these should be major releases.

## Tasks
- [ ] Run `npm outdated` and update the following packages:
    - `eslint`
    - `eslint-plugin-prettier`
    - `eslint-plugin-vue`
    - `lint-staged`
    - `prettier`
- [ ] `run npm lint` to update any linting errors that can be updated automatically
- [ ] Manually update any existing linting errors

## Test
- [ ] `run npm test:unit` and update any snapshot tests that may have changed due to the update
- [ ] `run npm build` and verify build process was successful
- [ ] Spot test 1-3 pages to verify functionality and and that there are not any JavaScript errors in the dev tools console

**Comment by SurenNeware** [comment]
Resolved by https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/39799
