### ISSUE TITLE
GUI : Terms - Consistent use of Host, server, and system

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#2896]
### Summary
We are using the host, server, and system terms throughout the application. They have been used interchanagably, which has generated confusion with some users. 

### Tasks
- [x] Identify and document all the use cases of these terms
- [x] Verify which term should be used consistently throughout the application
- [ ] Verify specific use of host with team

#### Host usage list
- [x] Factory Reset
    - Change all instances of `host` to `server`
- [ ] Firmware -> Two-file upload
- [x] Overview -> Network Hostname
    - Hostname is the redfish property name and used in other GUIs, so leave it as is
- [x] Network Settings -> Hostname
    - Hostname is the redfish property name and used in other GUIs, so leave it as is
- [x] Server power operations -> Host status, Host OS boot settings

### Assumption
We want to use the term `server` in place of `host`, and `system` throughout the application.

**Comment by derick-montague** [comment]
Verify if this is a systems wide story that requires content design involvement for the GUI.

**Comment by derick-montague** [comment]
I reached out to our content designer today to discuss further.

**Comment by derick-montague** [comment]
Follow up with Stephanie, our content designer was:

> We used system almost exclusively in Knowledge Center documentation. It's more holistic & seems preferable when referencing the hardware.  both server & host are going to be more software-related.

**Comment by derick-montague** [comment]
Steph and Stacia discussed this and determined that our path forward with `server`. The  next step is to identify any use of  host so they can be updated. In most cases, we were using `server` as that was the term we expected was preferred and understood by most users.

**Comment by derick-montague** [comment]
The determinations were made today and we need can move forward with some design feedback. All the changes are documented in the description.

**Comment by derick-montague** [comment]
Factory Reset Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/42884

**Comment by derick-montague** [comment]
Server power operations resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/42979
