### ISSUE TITLE
GUI : Design : Hardware Deconfiguration Policy

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#3213]
## Summary
The goal is to unify HW deconfiguration and `deconfiguration policies on the same page (may not need policies)` The proposed design that was created in September does not include the policy settings for HW deconfiguration.

Due to backend constraints, there are several aspects of the HW Deconfiguration design that have changed that include:
1. Different resources (Processors and DIMMs) will be listed in one table rather than in separate tabs. This implementation will not have a tabbed interface for different resources.

1. `Processor Chips` and `PCIe root complex` will not be part of the design
    ![image](https://user-images.githubusercontent.com/1183515/119678919-904cd380-be05-11eb-96ca-139cdc3d3163.png)

1.  The Overview tab will not be part of the design

1. Nodes will not be included in the first release
    ![image](https://user-images.githubusercontent.com/1183515/119678853-7f9c5d80-be05-11eb-9737-09f812e3c5d3.png)

1. We will not offer the user in the GUI the ability to delete all records
1.  We would like to show the users all the DIMM metrics (% configured, deconfigured in GB, Capacity in GB), which we are unclear if the backend will send this information.
    ![image](https://user-images.githubusercontent.com/1183515/119677642-82e31980-be04-11eb-9df1-2f7929aa7f03.png)
1. We would like to show users all the Processor metrics. FCO will need to be pulled from a FCO store value (implementation detail), but should be possible. Unclear if the other processor metrics will be part of the API or if FED will need to do calculations. 
    ![image](https://user-images.githubusercontent.com/1183515/119678280-01d85200-be05-11eb-8ac3-2b71623579d6.png)

## Tasks
- [ ] Verify if HW deconfiguration policy settings are required for GA1 or at all
    - MZ suggested they may not be needed and we need to verify
- [ ] Review existing design and break down to one table view rather than separate tabs
- [ ] Review backend with engineering to verify backend can provide the data required to meet user needs

## User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

## Use Case(s)
- [ ] Add use case(s)

## Design Goals
- [ ] Goal 1
- [ ] Goal 2
- [ ] Goal 3

## InVision Prototype
- [Current HW Deconfiguration design](https://ibm.invisionapp.com/share/X4O0DTDQWFU#/screens)

## Community
- [ ] Created design review story in webui-vue repo
- [ ] Sent email to community sharing the design review story

**Comment by derick-montague** [comment]
![image](https://user-images.githubusercontent.com/1183515/121459421-d8750580-c970-11eb-84b2-d3c86b53b1ba.png)

**Comment by derick-montague** [comment]
In a meeting today, it was determined that we may not add Deconfig policies for GA1 and the work to add policies to the Deconfig page may not be needed. This will be downstream work.

**Comment by derick-montague** [comment]
We met to discuss any changes needed to HW deconfiguration and notes can be found in the Design Exchange workshop.
