### ISSUE TITLE
GUI: FED : Downstream : System attention indicator

### ISSUE THREAD

**Issue by Su-kan** [ibm-openbmc/dev#3270]
## SME
BMC: TBD

## Overview
The system attention indicator is activated by the backend when there issues that need to be addressed with the machine. The indicator cannot be activated by a user, but it can be deactivated by a user. In the off state, it is expected that the UI will be standards label and value. It will be a toggle when it has been activated.

## User story
As an IBM Systems engineer, 
I need the user to be able to quickly determine if there is an issue with the system
So that they can report the concern to receive guidance

As a Power systems admin and Power Systems Associate Admin
I need to be able to easily determine if there is a system issue
So that I can troubleshoot or report the issue to IBM support 

## Tasks
- [ ] Verify the order of the toggles on the Hardware page. It could make sense to change System Attention and System Identify LED
- [ ] Add toggle to overview and hardware inventory
- [ ] Work with the BMC engineer to turn the indicator on for testing

## Final Invision Mockup
- https://ibm.invisionapp.com/d/main#/console/15347903/320050299/preview

#### Overview page - State: on
![image](https://user-images.githubusercontent.com/1183515/127491759-3a2991a3-3afe-468c-b783-378bef284ba9.png)

#### Overview page - State: off
![image](https://user-images.githubusercontent.com/1183515/127492458-dabd6835-4158-4a29-bf08-9b33cf527ee4.png)

#### Hardware and inventory page - State: on
![image](https://user-images.githubusercontent.com/1183515/127491786-c689837c-aa36-4efc-af55-5713ebb7d3c0.png)

#### Hardware and inventory page - State: off
![image](https://user-images.githubusercontent.com/1183515/127492507-18269638-7134-44bd-afca-a90998d1c9cd.png)

## cURL Commands
- [ ] Add cURL commands

## Notes
- UI is moving downstream as the backend will be ready by November

### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by Srisuk** [comment]
As per slack conversation [here](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1626177973266900?thread_ts=1626173116.265600&cid=C0Q6TQP5Z) with @lkammath , BE code will be available by spetember 2021.

**Comment by Srisuk** [comment]
As per the latest discussion with @lkammath, BE is currently working on MEX LED, and post this will start system attention LED([slack conversation](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1630590445238600?thread_ts=1626173116.265600&cid=C0Q6TQP5Z))
