### ISSUE TITLE
Icons: SVG Sprite implementation 

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#373]
## Overview
We have implemented icons using a combination of inline SVG's and background images and possibly some icon fonts that need to be converted to use an SVG sprite. This update will provide the following benefits: 
1. Consistent implementation, documentation, and ease of maintenance
2. Eliminate redundant SVG files that only vary by color (SVG sprites allow the icon paths to be filled via CSS)

## Tasks
- [ ] Use Webpack and the svg sprite loader and potentially any other needed loaders, e.g. `svoloader` for removing SVG meta information
- [ ] Update all existing icons to use the Carbon icon library
- [ ] Find and update all existing icons to use the icon sprite. 

## Resources
- https://css-tricks.com/svg-sprites-use-better-icon-fonts/
- https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use
- https://github.com/kisenka/svg-sprite-loader

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
This is outdated. We delivered a solution using directives. If we decide to update the front-end framework, we may need to revisit our svg implementation, but for now our directive approach works.
