### ISSUE TITLE
GUI: Boot options

### ISSUE THREAD

**Issue by gtmills** [ibm-openbmc/dev#404]
## Stakeholders
**SME**: @dkodihal, @santoshpuranik 
**PHYP SME:** Dave Stanton
**DR**: @nicoleconser 
**UX**: @jandraa 
**FED**: TBD

## Use Case
The intent of the boot options is to indicate "how" and "from where" to boot the OS.
- The "how" part is called boot mode and the options are: **Regular** (regular/default mode, such as boot to an OS), **Safe** (boot to a diagnostic/trouble-shooting mode), **Setup** (boot to BIOS setup) 
- The "where" part is called Boot Source and the options are: **Disk** (local hard disk), **External Media** (CD/DVD/USB, etc.), **Network** (a remote source over a network), **Default** (implementation defined source)

## InVision Prototype
https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319095138_1-_Boot_Options_-_System_On

## Design Issue
TBD

## Development Issue
**Redfish story**: https://github.com/ibm-openbmc/dev/issues/286

## Notes
- What: regular/default. safe mode, diagnostics mode, etc.
- Where:  hard disk, CDROM, network, etc.
- Santosh recently implemented the Redfish API around this.

### GUI Need
```curl -c cjar -b cjar -k -H "Content-Type: application/json" -X GET  https://${BMC_IP}/xyz/openbmc_project/control/host0/boot
{
  "data": {
    "BootMode": "xyz.openbmc_project.Control.Boot.Mode.Modes.Regular",
    "BootSource": "xyz.openbmc_project.Control.Boot.Source.Sources.Default"
  },
```

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jandraa** [comment]
There are 2 DBUS interfaces, one to save the boot option settings for the next reboot and another for subsequent reboots until this is changed. 

What is the use case for wanting to change the boot options for just the next boot versus all the following ones until a change is made? How often would a user would want to have different settings for the default and the next boot and is it enough to include it in the GUI?

**Comment by jandraa** [comment]
Will we support booting from the user's laptop? @santoshpuranik @dkodihal

**Comment by rfrandse** [comment]
refresh

**Comment by jandraa** [comment]
@nicoleconser 
- Need input on terminology for warm/cold vs immediate/orderly vs something else

**Comment by rfrandse** [comment]
refresh

**Comment by jandraa** [comment]
Questions for SMEs

- [ ] What happens after/during a reboot? How is a user informed that the reboot is done? 
- [ ] Where is the remote source over a network defined? / How is a user informed of it or change it?(for Boot Source) 
- [ ] We've heard different terminology for Boot Source and Boot Mode (PXE, single user mode, petitboot, boot to BIOS), what are these and how are they different from our current options?

**Comment by santoshpuranik** [comment]
> What happens after/during a reboot? Do we have a way of informing users that the reboot is done?
Not sure I followed this question. After a reboot, the expectation is that the computer boots back to the OS (I think the BMC state changes to indicate that).

> Where is the remote source over a network defined? / How is a user informed of it or change it?(for Boot Source)

> We've heard different terminology for Boot Source and Boot Mode (PXE, single user mode, petitboot, boot to BIOS), what are these and how are they different from our current options?

For the above questions, at least with respect to OpenPower systems, I have requested Stewart Smith to comment here.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
