### ISSUE TITLE
Keyboard accessibility testing

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#424]
# Team
*SME*: @derick-montague 

Manually test all panels for keyboard accessibility. Verify that:
- [X] All focusable and tabbable elements have a focus state
- [X] All elements, `<a>`, `<button>` can receive focus by tabbing, e.g. make sure semantic mark up is used opposed to markup like `<div>` elements with attached event listeners
- [X] The element tab order works as expected and the flow allows the user to easily navigate with their keyboard
- [X] The primary navigation elements are only tabbable/focusable when the navigation menu is open.
- [x] Check for `Skip to Content` link

## Issues
**TODO** : Create issues associated with this epic from the issues listed below

**Keyboard defects found are listed on comment below by @miramurali23  The defects are organized by pages in which they were found in.**

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by miramurali23** [comment]
### Accessibility Issues on Pages

Server Overview:
- When tabbing from turn on server LED to serial over LAN console there is no pause in focus state.
- When user selects edit, the focus state does not go directly on edit hostname modal, but tabs through the page before focusing on modal

Server Health -- Event Log:
- When the user selects a timezone the dropdown still displays after the user selection
- The focus never hits on the checkboxes on the page (the checkbox in the box header or the checkbox in the table overflow
- The focus never hits the arrow that collapses or expands further information on events

Server Control -- Manage Power Usage
- After selecting the toggle, the focus state is not seen until I click tab again and then it goes to the correct field.

Server Control -- Reboot BMC
- When user clicks reboot BMC the focus state does not go into the pop up modal for rebooting BMC. It first focuses on the content of the page and then goes in the modal

Serial Control --  Serial over LAN console:
- no tab focus on tis page at all. I would assume the keyboard should focus on the console.
- when you click on 'open in a new tab' (which you do not have access to on a keyboard) -- it takes you to a new page. On the new page there is a link to navigate back and that is not accessible on a keyboard

Server Configurations - Network settings:
- When you add Ipv4 the focus doesn't go on the add field
- DNS server button shifts focus back to add field so this pattern is inconsistent

Server Configuration - SNMP settings:
- After adding manager, the tab focus does not go on the added field
- Unless I shift tab, I am unable to navigate to any of the fields (ex: I try to tab through entire page from the start and it is unable to get to the focus state of any of the fields)

Server Configuration - Firmware

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
No longer valid. Will be addressed on all pages during vue rewrite. #1555
