### ISSUE TITLE
GUI : Design : Event Logs - Redfish

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#580]
## Stakeholders
**BMC SME**: @spinler, @dkodihal, @gtmills 
**RAS SME**: Justin Thaler

## Overview
- Audit Logs /redfish/v1/Managers/bmc/LogServices/Audit/
- Maintenance: /redfish/v1/Managers/bmc/LogServices/Maintenance/
-  Events: /redfish/v1/Managers/bmc/LogServices/Events/
-  Progress/Boot Logs: /redfish/v1/Managers/bmc/LogServices/Boot/
- Correctable/Hidden (CElogin only): /redfish/v1/Managers/bmc/LogServices/Correctable/ 

Some of these Event logs will have a link to PELs. Should the link be in the log?
PELs will be a file with hex data on the BMC. 
PELs will not be displayed on the GUI. 

Justin: 
For audit logs, I'd recommend separating out things like the machine power state changing, from the user triggering it, so Support can find out when a box crashed/ went down/ came up, in relation to the problem.
My plan to deal with Audit logs was to have them in their own LogService, so when we collect service data we don't have to scrub the logs for GDPR compliance, just not collect the audit log.

### Related Issue
GUI: Design: Event log page redesign based on redfish and user feedback: #650

## Use Case
As an IBM CE, I need to be able to review all correctable logs along with all other logs. 

## Tasks
- [x] Evaluate the following design and update the prototype in Invision.
- [x] Reviewing the design in issue #650, there are components within the design that need to be updated before the development team can move forward. 
- [x] Revisit the Event log redesign to assure it is scalable and can handle the updated PEL logs

![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/7eeefc58-9d02-40df-96b3-f61c91b6b5fa)

## InVision Prototype
Found in #650
Hidden logs- https://ibm.invisionapp.com/share/JGO0304UF9K#/319541134_01-Event-Logs-06

## Design Issue (webui-vue)
---

## Development Issue 
---

## References/Resources
- [eBMC Feature Item: 2.5.3](https://ibm.box.com/s/j15ux3yfjycy4or4azbqyhqq11lbya0r)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
@ryanarnell - Is this the continuation of the Event logs story?

**Comment by derick-montague** [comment]
This design needs to evolve due to new logs that are being added. This story scope has increased.

**Comment by nicoleconser** [comment]
FYI from Justin Thaler, Michael, Todd - "we should start generating logs when crossing thresholds. This would also be a post GA1 function" (referring to sensor thresholds) https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1588267915228500

**Comment by nicoleconser** [comment]
FYI @ryanarnell, I started looking at #1432 (Show Gard records and Clear Gard) (part of Hardware Deconfiguration epic), and there are discussions happening in Dhruvaraj Subhashchandran's Gerrit design doc (comments by Patrick Williams, Andrew Jeffrey) that might impact error logs —  specifically "The guard records will be presented as an extension to logs." Also documented this on the [Feature Discovery doc](https://ibm.box.com/s/c93klpdyldne9hz1or25f3akc4r7pw3e).

**Comment by ryanarnell** [comment]
The hidden logs feature which we plan to show in the main logs page if the logged in user have the privilege. This prototype which needs to be further tested with PEs can be found here- https://ibm.invisionapp.com/share/JGO0304UF9K#/319541134_01-Event-Logs-06

**Comment by derick-montague** [comment]
Slack conversation regarding all logs in one table: https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1592238708364400

**Comment by ben-bacon** [comment]
1. Is this design scalable?
- Yes, with design guide updates to tables, this should be good. May want to look into a pattern for controlling which columns are seen if the number of columns increases. Or moving the quick description into the accordion expansion. (pertains to modified date and time inclusion).

2. are the status icons the most accessible option?
- In the carbon library, yes. We could introduce another shape to add a layer differentiation to the status icons, but that would require a custom icon (which is fine if that is the route we want to take). A suggestion I would make though is to not include an icon at all for "OK" status, this would cut down on the attention required of the user and simultaneously give all status icons in this table a unique 'shape' or 'container'. But as it stands now, no accessibility standards are being violated visually. 

3. Is the export icon the best available variation possible?
- It is pretty close to other standards. I have heard users confused by it when asked to focus on it and discern it's meaning, but when breezing through an app they are able to make the cognitive leap. an alternative option would be the "document export" icon 
<img width="199" alt="image" src="https://user-images.githubusercontent.com/52676199/86177641-a0244080-baec-11ea-8312-e8c1bc1e3dc8.png">.

**Comment by derick-montague** [comment]
> A suggestion I would make though is to not include an icon at all for "OK" status, this would cut down on the attention required of the user and simultaneously give all status icons in this table a unique 'shape' or 'container'.

Agree! I think this is a great suggestion.

> But as it stands now, no accessibility standards are being violated visually.

I don't think we need to give icons different shapes either. I only wonder about what meaning the diagonal line actually conveys to users. I know the the Carbon team has done extensive testing. It's just not seem as common, but that is just my perspective. When I search google, we see exclamations (which we use for warnings) and we we X's. I was wondering less about accessibility and more about interpretability. What are your thoughts?

![image](https://user-images.githubusercontent.com/1183515/86261648-7159a900-bb84-11ea-8924-fcb4914f5d7b.png)

>  an alternative option would be the "document export" icon

This makes more sense to me. I'm not sure how that is intended to be used in comparison to the export button, but it makes more sense to me.

![image](https://user-images.githubusercontent.com/1183515/86261196-dcef4680-bb83-11ea-8454-4bd7e550407b.png)

**Comment by ben-bacon** [comment]
> When I search google, we see exclamations (which we use for warnings) and we we X's. I was wondering less about accessibility and more about interpretability. What are your thoughts?

I see your point, but the only shape that the triangle "warning" can use is the exclamation point. If we are worried about the user not grasping the ;eve; of urgency with the 'slash' or 'do not enter' icon for "critical"  then we should use the 'misuse' variant. 
<img width="196" alt="image" src="https://user-images.githubusercontent.com/52676199/86272867-e634df00-bb94-11ea-9756-3d4c212234de.png">

**Comment by derick-montague** [comment]
How do you feel about the use of the error vs misuse icon. I am ok using error in the application for critical if you think it will be easily understood without the use of color.

**Comment by ben-bacon** [comment]
Personally I think the 'misuse' icon conveys more urgency, better-safe-than-sorry. It can also be used in the notifications for errors when those get pulled in.

**Comment by derick-montague** [comment]
I agree. I'll add a story to
1. Replace `error` with `misuse` icon
1. Replace `export` with `document-export` icon
1. Remove the icon for the items that are `ok`

Thank you!

**Comment by ben-bacon** [comment]
![image](https://user-images.githubusercontent.com/52676199/86368014-53527e00-bc42-11ea-910a-c9cca269120d.png)
