### ISSUE TITLE
GUI: CPU throttle

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#588]
## Stakeholders
**SME**: @spinler, Martha Broyles

### Summary
If the temps get too high, instead of burning down the system or getting too hot, crank up the fans, if still too high, cut down on the power to processor (lower voltage rate) and memory (slow down transaction rate). This is called throttling. As a user, it is important to know when throttling is happening because it will affect my performance. 

Throttle events should not trigger Call Home – they're likely caused by another problem that SHOULD have an error log entry and DOES call home. Users have expressed a need for an event log entry + email notification, either via SNMP/HMC, SNMP/BMC, or Remote logging server on BMC. 

Emailing would require some configuration to use a mail server and an account to use on the mail server. Also obviously enabling the notification method from the BMC as well.

### Assumptions
Similar to displaying temperature sensors, we also need to display the throttling sensors.  All we need to show is the current status of the sensors, e.g. if they are throttling or not.

### User Story
As a <type of user>
I need to <perform some activity>
in order to <complete some task or accomplish some goal>

## InVision Prototype
[Iteration 1](https://ibm.invisionapp.com/share/8ENYRVXAPFD#/319199604_01-CPU-GPU-Throttle)

### Tasks
- [ ] Create design review story in webui-vue repo
- [ ] Send email to community sharing the design review story
- [ ] Post in story in the discord webui channel

## References/Resources
- eBMC Feature 2.3.3
- [Discovery Notes](https://ibm.ent.box.com/notes/450253785702)
- 
### UX Flow / Interaction Requirements
- [ ] Feature breakdown

### cURL Commands and Redfish Response
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by jandraa** [comment]
Needs to be done before GPU Throttle.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by jandraa** [comment]
Likely will not support in the GUI; waiting on confirmation from @mzipse and Todd Rosedahl.

The main reasoning is that we cannot get an instant read of CPUs from the OCC so it could often be outdated information by the time a user sees it.

**Comment by derick-montague** [comment]
Determined that we will want to support throttle for 9.5.x. Moving these to backlog.

**Comment by rfrandse** [comment]
refresh

**Comment by ryanarnell** [comment]
https://ibm.ent.box.com/notes/450253785702 -- discovery notes

**Comment by ryanarnell** [comment]
Conversations with @spinler indicated that:

GPU Power is a sensor and does not require design work
GPU Throttle is not ready enough to determine if GUI work is needed or not based on the SME feedback provided to @jandraa.
Min/Max is still being researched

**Comment by ryanarnell** [comment]
Likely will not support in the GUI; waiting on confirmation from @mzipse and Todd Rosedahl.

The main reasoning is that we cannot get an instant read of GPUs from the OCC so it could often be outdated information by the time a user sees it.

**Comment by derick-montague** [comment]
https://github.com/ibm-openbmc/dev/issues/958#issuecomment-707949856

**Comment by derick-montague** [comment]
@gtmills is this  just an display in sensors?

**Comment by derick-montague** [comment]
Posted the question on milestone to Todd. Will follow up after 1/4/21.

**Comment by rfrandse** [comment]
tracking in jira
