### ISSUE TITLE
GUI : Configure I/O Enclosure Settings

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#617]
## Stakeholders
**BMC SME**: Travis Pizel, Santosh Puranik
**RAS SME**: ~~Justin Thaler~~
**PHYP SME**: Adam Stallman
**SME**: Tom Sand and Matt Spinler

### Summary
It shows the enclosures that are part of the system (both the system and unit itself, as well as external I/O drawers), their type, model, serial number, firmware version and location code in an easy to read table. A customer may use it if they are asked what firmware version is active in a drawer (drawers have their own firmwares which are not the same as host/BMC firmware).  They may also use the location code to correlate other information they have about the system.

### User Scenario
- Used by IBM Support during problem determination that may be related to an enclosure.
- Used by customers to check firmware version of the enclosure or its location code.
- When an enclosure is repurposed and new servers are installed on it, at that time the data needs to be updated.

### InVision Prototype
https://ibm.invisionapp.com/d/main#/console/15347903/320003007/preview

### Tasks
- [ ] Create design review story in webui-vue repo
- [ ] Send email to community sharing the design review story
- [ ] Post in story in the discord webui channel

### References
- eBMC Feature Item 4.10
- [Discovery folder](https://ibm.box.com/s/scd3y03tkcmz4le8ed5ybo9ia1a0xbc4)
- [Discussion with PEs and Backend Dev](https://ibm.ent.box.com/notes/817981035218?s=53rb85sccc0dvffw0ltqcb38fg7y62cr)

### UX Flow / Interaction Requirements
- Click on settings to update server information. [Screen here](https://ibm.invisionapp.com/d/main#/console/15347903/320003008/preview).
- Enclosure information cannot be read if system is powered off. Show an inline notification for this, as well as a message in the empty table. [Screen here.](https://ibm.invisionapp.com/d/main#/console/15347903/320003010/preview)
- Current unknowns: What will be the format for Firmware Version? Will backend send 2 separate keys for current and next firmware versions, or will they be combined in one key?

### cURL Commands and Redfish Response
**This will be based on the Chassis schema (refer Hardware Inventory story)**
- [ ] Add Redfish response
- [ ] Add cURL commands

### Notes
- [ ] Any known API workarounds
- [ ] Any server-side functionality WIP

#### Browser Tests (Chrome, Firefox, Safari (Mac), Edge (Windows))
- [ ] Tested responsive layout on supported viewport sizes
- [ ] Verified functionality works as expected, e.g. success and failure use cases
- [ ] Resolved any JavaScript errors thrown to the console

#### Accessibility Tests
- [ ] Verified markup is semantic
- [ ] No reported issues in IBM Accessibility Checker (Free open source tool) https://www.ibm.com/able/toolkit/tools/

#### Test Hooks
- [ ] Verify need for `data-test-id` hooks with test team

**Comment by derick-montague** [comment]
It's not clear what work is required for the GUI.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
Discussions in the Feature Sync meeting on 6/15/20 suggested by @mzipse that this may be legacy functionality that may require minimal to no GUI work.

**Comment by derick-montague** [comment]
I/O Adapter Enlarged Capacity - https://www.ibm.com/support/knowledgecenter/9080-M9S/p9hby/ioadapter.htm

**Comment by nicoleconser** [comment]
> I/O Adapter Enlarged Capacity - https://www.ibm.com/support/knowledgecenter/9080-M9S/p9hby/ioadapter.htm

^ That function is unrelated to this, even though they both have I/O in the name.

**Comment by derick-montague** [comment]
Does System Power Control Network need to be supported? [Slack conversation](https://ibm-systems-power.slack.com/archives/C0Q6TQP5Z/p1597353771186000)

**Comment by derick-montague** [comment]
Set the milestone to be the same as the engineering milestone, A.1.211

**Comment by derick-montague** [comment]
![image](https://user-images.githubusercontent.com/1183515/104365317-76a59200-54dd-11eb-9991-b11aa383e14f.png)
![image](https://user-images.githubusercontent.com/1183515/104365407-92a93380-54dd-11eb-8285-a25e760bb285.png)

**Comment by derick-montague** [comment]
![image](https://user-images.githubusercontent.com/1183515/104367741-dbaeb700-54e0-11eb-8114-dbc9bf584895.png)

**Comment by nicoleconser** [comment]
A discussion around this began in Jan 2020 during the IA card sort prep — all findings are documented in the feature's Discovery doc: https://ibm.box.com/s/scd3y03tkcmz4le8ed5ybo9ia1a0xbc4

**Comment by derick-montague** [comment]
> A discussion around this began in Jan 2021 during the IA card sort prep — all findings are documented in the feature's Discovery doc: https://ibm.box.com/s/scd3y03tkcmz4le8ed5ybo9ia1a0xbc4

There is also a [conversation in slack](https://ibm-systems.slack.com/archives/C0Q6TQP5Z/p1610140707166000?thread_ts=1610140429.165800&cid=C0Q6TQP5Z)

**Comment by nicoleconser** [comment]
Discussion w/ engineers about what needs to change on this page for eBMC can be found in [OpenBMC GUI Feature & Function Q+As](https://ibm.box.com/s/bod05encex6ifxbf3ml2fxl6fdb2gggh) doc.

**Comment by ParishrutB** [comment]
Current unknowns:
1. What will be the format for Firmware Version? Will backend send 2 separate keys for current and next firmware versions, or will they be combined in one key?
2. Whether this story will be upstream or downstream. Gunnar & Santosh mentioned that they will try to upstream it.

**Comment by ParishrutB** [comment]
Santosh mentioned that this is based on the Chassis schema and will most definitely be an upstream story.

**Comment by mzipse** [comment]
This work is complete.  We have implemented the req'd Enclosure settings.  Closing.
