### ISSUE TITLE
Define PLDM BIOS attribute for code update policy

### ISSUE THREAD

**Issue by dkodihal** [ibm-openbmc/dev#804]

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by dkodihal** [comment]
- [ ] Defining the BIOS attribute in the BIOSEnum JSON : providing the name, default values, D-Bus backing (if exists).
- [ ] Define D-Bus interface for enabling host initiated inband code updates. This should be a phosphor DBUS interface.
- [ ] Implementation of the D-Bus interface : should be a new setting.
- [ ] Unit Test : verify current D-Bus value is reflected in the attribute value table.

**Comment by dkodihal** [comment]
Investigate if this can be controlled by a user.

**Comment by tomjoseph83** [comment]
The inband-code-update BIOS attribute was not set via GUI/out-of-band on the legacy systems. If the HMC is connected then inband-code-update is not allowed and if HMC is not connected it is allowed. So this BIOS attribute will depend ideally on a D-Bus property which will indicate the connection status of the HMC.

**Comment by sampmisr** [comment]
We seem to have the bios attribute implemented
