### ISSUE TITLE
GUI: Move phosphor-webui to use ESLint and Prettier

### ISSUE THREAD

**Issue by derick-montague** [ibm-openbmc/dev#891]
## As Is
The phosphor-webui is using clang-format, as well as the CI build process. The clang-format does not provide the formatting as we expect it and in some cases forces a format that is not a best practice and  is rejected by the CI build process.

## To Be
Talk to community to move to ESLint using the Goggle shared config and the ESLint recommended settings for JS and Prettier for SCSS.

## Tasks
- [ ] Add: eslint and prettier configs
- [ ] Update CI script: format-code.sh
- [ ] Update: All JS and SCSS files
- [ ] Update: https://github.com/openbmc/docs/blob/master/CONTRIBUTING.md#javascript
- [ ] Update: https://github.com/openbmc/docs/tree/master/style

## Examples Formatting issues with clang-format
![image.png](https://images.zenhubusercontent.com/57e6780495e42b6c5ba963ac/84ba50fb-7237-4430-8645-94f77932f77e)

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
staying with clang-format due to difficulty with CI customization. Will revisit in the future.
