### ISSUE TITLE
eBMC GUI translation support

### ISSUE THREAD

**Issue by mzipse** [ibm-openbmc/dev#974]
## Stakeholders
**SME**: TBD

## Overview
There is a requirement to translating eBMC GUI content with the same languages that FSP/ASMI was supporting.  We'll need to catch on of the translation cycles (typically for the fall release).  Group 1 languages are supported (see #1302). My (@mzipse) understanding is that Chirag Sharma had coordinated that previously for ASMI menus on FSP. 

## Questions

- [x] Since not all content is translated, what dynamic content will be translated by the backend and is it supported in the REST or Redfish API?

Any information coming from the backend that is static will need to be mapped in the front-end in order to be translated.

- [x] If dynamic content translation needs to be supported, is the engineering team planning to accept locale info in either the REST API or Redfish requests in order to send translated content in the response for dynamic info?

That is not the plan currently. It may be accommodated in the future.

- [x] Do we need the option for a user to choose their language of choice in the event that their native language is not supported and they want to choose a different language other than English?

Yes. The UI will allow the user to change the language on the login page, as well as after logging in.

- [ ] Are there any RTL (right to left) languages that require support?

## Use Case
TBD

## InVision Prototype
TBD

## Design Issue (phosphor-webui)
TBD

## Development Issue 
TBD

## References/Resources
- [feature discovery folder](https://ibm.box.com/s/vym58ukem44b5mb3dq9maou71rb03229)
- user research notes*: 
- user research synthesis: 

*This folder is restricted in accordance with GDPR guidelines.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by derick-montague** [comment]
I added all the translation stories to this Epic. There is a caveat that all pages still need to be translated during the vue rewrite. This Epic only includes the stories for setting up the service, updating the existing vue rewrite pages and the task to send the information for translation.

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh

**Comment by rfrandse** [comment]
refresh
